import type { HistoricalEvent } from './schema';

const brit = (label: string, slug: string) => ({
  label,
  publisher: 'Encyclopædia Britannica',
  url: `https://www.britannica.com/${slug}`,
  kind: 'encyclopedia' as const,
});
const nasa = (label: string, url: string) => ({ label, publisher: 'NASA', url, kind: 'institution' as const });

/**
 * Historical events carry month/day where the date is well established, which
 * is what powers „ამ დღეს ისტორიაში". Events whose exact day is disputed keep
 * only a year — the daily module degrades to "this month / nearest anniversary"
 * rather than inventing a date.
 */
export const EVENTS: HistoricalEvent[] = [
  /* ---------------- მეცნიერების ისტორია ---------------- */
  {
    id: 'e-principia',
    subjectId: 'physics',
    title: { ka: 'გამოქვეყნდა ნიუტონის „ბუნებისმეტყველების მათემატიკური საწყისები"' },
    year: 1687,
    month: 7,
    day: 5,
    region: 'science',
    summary: {
      ka: 'ნიუტონმა ერთ სისტემაში გააერთიანა მოძრაობის კანონები და მსოფლიო მიზიდულობა და აჩვენა, რომ ერთი და იგივე მათემატიკა აღწერს როგორც დაცემულ სხეულს, ისე პლანეტების ორბიტებს.',
    },
    cause: { ka: 'ჰალეიმ ნიუტონს ჰკითხა, რა ფორმის ორბიტა გამოდიოდა უკუკვადრატული ძალიდან — და აღმოჩნდა, რომ ნიუტონს პასუხი უკვე გამოთვლილი ჰქონდა, ოღონდ არ გამოექვეყნებინა.' },
    consequence: { ka: 'დაიბადა კლასიკური მექანიკა. მომდევნო 200 წელი ფიზიკა ძირითადად ამ ჩარჩოში ვითარდებოდა, სანამ ფარდობითობა და კვანტური თეორია არ გამოჩნდა.' },
    topicIds: ['newton-laws', 'gravity'],
    sources: [brit('Principia', 'topic/Philosophiae-Naturalis-Principia-Mathematica')],
  },
  {
    id: 'e-galileo-moons',
    subjectId: 'astronomy',
    title: { ka: 'გალილეომ იუპიტერის თანამგზავრები აღმოაჩინა' },
    year: 1610,
    month: 1,
    day: 7,
    region: 'science',
    summary: {
      ka: 'ტელესკოპით გალილეომ იუპიტერის გვერდით ოთხი „ვარსკვლავი" დაინახა, რომლებიც ღამიდან ღამემდე ადგილს იცვლიდნენ. მალე მიხვდა, რომ ისინი იუპიტერს უვლიდნენ.',
    },
    cause: { ka: 'ტელესკოპის გაუმჯობესებამ საშუალება მისცა, ცა ისე დაენახა, როგორც მანამდე შეუძლებელი იყო.' },
    consequence: { ka: 'ეს იყო პირველი პირდაპირი მტკიცებულება, რომ ყველაფერი დედამიწის გარშემო არ ბრუნავს — გეოცენტრული სისტემისთვის სერიოზული დარტყმა.' },
    topicIds: ['solar-system'],
    sources: [brit('Galileo', 'biography/Galileo-Galilei')],
  },
  {
    id: 'e-periodic-table',
    subjectId: 'chemistry',
    title: { ka: 'მენდელეევმა პერიოდული სისტემა წარადგინა' },
    year: 1869,
    month: 3,
    day: 6,
    region: 'science',
    summary: {
      ka: 'რუსეთის ქიმიურ საზოგადოებაში წაკითხულ მოხსენებაში ელემენტები ატომური მასის მიხედვით დალაგდნენ და გამოჩნდა, რომ თვისებები პერიოდულად მეორდება.',
    },
    consequence: { ka: 'ცხრილმა არა მხოლოდ ცნობილი ელემენტები დაალაგა, არამედ იწინასწარმეტყველა აღმოუჩენელი. როცა გალიუმი და გერმანიუმი იპოვეს, პროგნოზები გამართლდა.' },
    topicIds: ['periodic-table'],
    sources: [brit('Periodic table', 'science/periodic-table')],
  },
  {
    id: 'e-origin-species',
    subjectId: 'biology',
    title: { ka: 'გამოიცა დარვინის „სახეობათა წარმოშობა"' },
    year: 1859,
    month: 11,
    day: 24,
    region: 'science',
    summary: {
      ka: 'პირველივე დღეს მთელი ტირაჟი გაიყიდა. წიგნში დარვინმა ბუნებრივი გადარჩევის მექანიზმი და მისი დამადასტურებელი მტკიცებულებები წარმოადგინა.',
    },
    cause: { ka: 'ალფრედ უოლესმა დარვინს მსგავსი იდეის ხელნაწერი გამოუგზავნა — სწორედ ამან აიძულა, გამოქვეყნება აღარ გადაედო.' },
    consequence: { ka: 'ბიოლოგიამ მიიღო გამაერთიანებელი თეორია. დღეს ევოლუცია თანამედროვე ბიოლოგიისა და მედიცინის საფუძველია.' },
    topicIds: ['evolution'],
    sources: [brit('On the Origin of Species', 'topic/On-the-Origin-of-Species')],
  },
  {
    id: 'e-xrays',
    subjectId: 'physics',
    title: { ka: 'რენტგენმა X-სხივები აღმოაჩინა' },
    year: 1895,
    month: 11,
    day: 8,
    region: 'science',
    summary: {
      ka: 'კათოდური მილით ექსპერიმენტისას რენტგენმა შენიშნა, რომ მოშორებით მდებარე ეკრანი ანათებდა — თუმცა მილი შავი მუყაოთი იყო დაფარული.',
    },
    consequence: { ka: 'რამდენიმე თვეში ექიმებმა უკვე ძვლების სურათებს იღებდნენ. ეს ერთ-ერთი ყველაზე სწრაფად დანერგილი სამეცნიერო აღმოჩენაა მედიცინის ისტორიაში.' },
    topicIds: ['light', 'atom-structure'],
    sources: [brit('Wilhelm Röntgen', 'biography/Wilhelm-Rontgen')],
  },
  {
    id: 'e-general-relativity',
    subjectId: 'physics',
    title: { ka: 'აინშტაინმა ზოგადი ფარდობითობის განტოლებები წარადგინა' },
    year: 1915,
    month: 11,
    day: 25,
    region: 'science',
    summary: {
      ka: 'პრუსიის მეცნიერებათა აკადემიაში წაკითხულ მოხსენებაში აინშტაინმა გრავიტაციის სრულიად ახალი აღწერა შემოგვთავაზა: მასა ღუნავს სივრცე-დროს.',
    },
    consequence: { ka: 'თეორიამ ახსნა მერკურის ორბიტის ანომალია და იწინასწარმეტყველა სინათლის გადახრა. 1919 წლის დაბნელებამ ეს დაადასტურა.' },
    topicIds: ['relativity', 'black-holes'],
    sources: [brit('General relativity', 'science/general-relativity')],
  },
  {
    id: 'e-fission',
    subjectId: 'chemistry',
    title: { ka: 'აღმოაჩინეს ბირთვული დაშლა' },
    year: 1938,
    month: 12,
    day: 17,
    region: 'science',
    summary: {
      ka: 'ჰანმა და შტრასმანმა ურანის ნეიტრონებით დასხივებისას ბარიუმი აღმოაჩინეს. ლიზე მაიტნერმა და ოტო ფრიშმა ახსნეს, რომ ბირთვი ორად იყოფოდა.',
    },
    consequence: { ka: 'შედეგებმა როგორც ბირთვულ ენერგეტიკამდე, ისე ბირთვულ იარაღამდე მიგვიყვანა — ერთ-ერთი ყველაზე მკვეთრი მაგალითი იმისა, რომ აღმოჩენას თავისთავად მიმართულება არ აქვს.' },
    sources: [brit('Nuclear fission', 'science/nuclear-fission')],
  },
  {
    id: 'e-dna-structure',
    subjectId: 'biology',
    title: { ka: 'გამოქვეყნდა დნმ-ის ორმაგი სპირალის სტრუქტურა' },
    year: 1953,
    month: 4,
    day: 25,
    region: 'science',
    summary: {
      ka: 'Nature-ში ერთდროულად სამი სტატია გამოქვეყნდა. უოტსონისა და კრიკის მოდელი ფრანკლინისა და უილკინსის რენტგენოგრაფიულ მონაცემებს ეყრდნობოდა.',
    },
    cause: { ka: 'როზალინდ ფრანკლინის „ფოტო 51" აჩვენებდა სპირალისთვის დამახასიათებელ დიფრაქციულ სურათს.' },
    consequence: { ka: 'სტრუქტურამ თავისთავად ახსნა, როგორ კოპირდება მემკვიდრეობითი ინფორმაცია. აქედან დაიწყო მოლეკულური ბიოლოგია.' },
    topicIds: ['dna', 'genetics'],
    sources: [
      {
        label: 'Watson & Crick, "Molecular Structure of Nucleic Acids", Nature 171',
        publisher: 'Nature',
        url: 'https://www.nature.com/articles/171737a0',
        year: 1953,
        kind: 'journal',
      },
    ],
  },
  {
    id: 'e-sputnik',
    subjectId: 'astronomy',
    title: { ka: 'ორბიტაზე გავიდა პირველი ხელოვნური თანამგზავრი' },
    year: 1957,
    month: 10,
    day: 4,
    region: 'science',
    summary: {
      ka: '„სპუტნიკ 1" 58 სანტიმეტრის დიამეტრის ლითონის სფერო იყო, რომელიც რადიოსიგნალს გადმოსცემდა. მისი მიღება მოყვარულ რადიომოყვარულებსაც შეეძლოთ.',
    },
    consequence: { ka: 'დაიწყო კოსმოსური რბოლა. ერთ წელიწადში შეიქმნა NASA, კოსმოსური კვლევა კი სახელმწიფო პრიორიტეტად იქცა.' },
    sources: [nasa('Sputnik and the Dawn of the Space Age', 'https://www.nasa.gov/history/sputnik/')],
  },
  {
    id: 'e-gagarin',
    subjectId: 'astronomy',
    title: { ka: 'ადამიანი პირველად გავიდა კოსმოსში' },
    year: 1961,
    month: 4,
    day: 12,
    region: 'science',
    summary: {
      ka: 'იური გაგარინმა „ვოსტოკ 1"-ით დედამიწის ერთი სრული შემოვლა შეასრულა. ფრენა დაახლოებით 108 წუთს გაგრძელდა.',
    },
    sources: [brit('Yuri Gagarin', 'biography/Yuri-Gagarin')],
  },
  {
    id: 'e-apollo11',
    subjectId: 'astronomy',
    title: { ka: 'ადამიანი მთვარეზე დაეშვა' },
    year: 1969,
    month: 7,
    day: 20,
    region: 'science',
    summary: {
      ka: 'ნილ არმსტრონგი და ბაზ ოლდრინი „აპოლო 11"-ის სადესანტო მოდულით მთვარის ზედაპირზე დაეშვნენ. მისიამ დედამიწაზე მთვარის გრუნტის ნიმუშები ჩამოიტანა.',
    },
    consequence: { ka: 'ჩამოტანილი ნიმუშები დღემდე ისწავლება და სწორედ მათ საფუძველზე ჩამოყალიბდა მთვარის წარმოშობის თანამედროვე თეორია.' },
    sources: [nasa('Apollo 11 Mission Overview', 'https://www.nasa.gov/mission/apollo-11/')],
  },
  {
    id: 'e-arpanet',
    subjectId: 'cs',
    title: { ka: 'გაიგზავნა პირველი შეტყობინება ARPANET-ში' },
    year: 1969,
    month: 10,
    day: 29,
    region: 'science',
    summary: {
      ka: 'UCLA-დან სტენფორდში სიტყვა „LOGIN"-ის გაგზავნა სცადეს. სისტემა ორი ასოს შემდეგ გაითიშა — პირველი გადაცემული შეტყობინება „LO" აღმოჩნდა.',
    },
    consequence: { ka: 'ARPANET გახდა ის ქსელი, რომლისგანაც ინტერნეტი განვითარდა.' },
    topicIds: ['networks', 'computing-history'],
    sources: [brit('ARPANET', 'topic/ARPANET')],
  },
  {
    id: 'e-www-proposal',
    subjectId: 'cs',
    title: { ka: 'ტიმ ბერნერს-ლიმ ვებგვერდების სისტემა შემოგვთავაზა' },
    year: 1989,
    month: 3,
    day: 12,
    region: 'science',
    summary: {
      ka: 'CERN-ში წარდგენილ წინადადებაში აღწერილი იყო ჰიპერტექსტური სისტემა დოკუმენტების დასაკავშირებლად. ხელმძღვანელის რეზოლუცია იყო: „ბუნდოვანია, მაგრამ საინტერესო".',
    },
    consequence: { ka: '1993 წელს CERN-მა ვების ტექნოლოგიები საჯარო სარგებლობაში, უფასოდ გადასცა — სწორედ ამან განაპირობა მისი სწრაფი გავრცელება.' },
    topicIds: ['networks', 'computing-history'],
    sources: [
      {
        label: 'The birth of the Web',
        publisher: 'CERN',
        url: 'https://home.cern/science/computing/birth-web',
        kind: 'institution',
      },
    ],
  },
  {
    id: 'e-hubble-launch',
    subjectId: 'astronomy',
    title: { ka: 'ორბიტაზე გავიდა ჰაბლის კოსმოსური ტელესკოპი' },
    year: 1990,
    month: 4,
    day: 24,
    region: 'science',
    summary: {
      ka: 'ტელესკოპი შატლ „დისკავერიმ" გაიყვანა. მალევე აღმოჩნდა, რომ მთავარ სარკეს ფორმის დეფექტი ჰქონდა.',
    },
    consequence: { ka: '1993 წელს ასტრონავტებმა ორბიტაზევე დაამონტაჟეს მაკორექტირებელი ოპტიკა. ეს კოსმოსში შეკეთების ერთ-ერთი ყველაზე რთული ოპერაცია იყო.' },
    topicIds: ['galaxies', 'cosmology'],
    sources: [nasa('Hubble Space Telescope', 'https://science.nasa.gov/mission/hubble/')],
  },
  {
    id: 'e-pale-blue-dot',
    subjectId: 'astronomy',
    title: { ka: '„ვოიაჯერ 1"-მა დედამიწა 6 მილიარდი კილომეტრიდან გადაუღო' },
    year: 1990,
    month: 2,
    day: 14,
    region: 'science',
    summary: {
      ka: 'კარლ საგანის დაჟინებული თხოვნით კამერა უკან შემოატრიალეს. სურათზე დედამიწა ერთი პიქსელზე ნაკლებია — „მკრთალი ცისფერი წერტილი".',
    },
    sources: [nasa('Pale Blue Dot', 'https://science.nasa.gov/resource/pale-blue-dot/')],
  },
  {
    id: 'e-human-genome',
    subjectId: 'biology',
    title: { ka: 'დასრულდა ადამიანის გენომის პროექტი' },
    year: 2003,
    month: 4,
    day: 14,
    region: 'science',
    summary: {
      ka: '13 წლის საერთაშორისო მუშაობის შემდეგ გამოცხადდა ადამიანის გენომის თანმიმდევრობის დასრულება. მონაცემები თავიდანვე საჯაროდ ხელმისაწვდომი გახდა.',
    },
    consequence: { ka: 'გენომის სექვენირების ღირებულება მას შემდეგ მილიონობითჯერ შემცირდა — ეს დღეს რუტინული სამედიცინო პროცედურაა.' },
    topicIds: ['dna', 'genetics'],
    sources: [
      {
        label: 'Human Genome Project',
        publisher: 'National Human Genome Research Institute (NIH)',
        url: 'https://www.genome.gov/human-genome-project',
        kind: 'institution',
      },
    ],
  },
  {
    id: 'e-higgs',
    subjectId: 'physics',
    title: { ka: 'CERN-მა ჰიგსის ბოზონის აღმოჩენა გამოაცხადა' },
    year: 2012,
    month: 7,
    day: 4,
    region: 'science',
    summary: {
      ka: 'ATLAS და CMS ექსპერიმენტებმა დამოუკიდებლად დააფიქსირეს ახალი ნაწილაკი დაახლოებით 125 გევ მასით — ზუსტად იქ, სადაც სტანდარტული მოდელი მიუთითებდა.',
    },
    cause: { ka: 'ნაწილაკის არსებობა 1964 წელს იქნა ნაწინასწარმეტყველები — ექსპერიმენტულ დადასტურებას თითქმის ნახევარი საუკუნე დასჭირდა.' },
    topicIds: ['quantum'],
    sources: [
      {
        label: 'The Higgs boson',
        publisher: 'CERN',
        url: 'https://home.cern/science/physics/higgs-boson',
        kind: 'institution',
      },
    ],
  },
  {
    id: 'e-gravitational-waves',
    subjectId: 'physics',
    title: { ka: 'პირველად დაფიქსირდა გრავიტაციული ტალღები' },
    year: 2015,
    month: 9,
    day: 14,
    region: 'science',
    summary: {
      ka: 'LIGO-მ დააფიქსირა სიგნალი ორი შავი ხვრელის შერწყმისგან. აღმოჩენა 2016 წლის თებერვალში გამოცხადდა.',
    },
    cause: { ka: 'გრავიტაციული ტალღები აინშტაინმა 1916 წელს იწინასწარმეტყველა, თუმცა თვითონ ეჭვობდა, ოდესმე თუ გახდებოდა მათი დაფიქსირება შესაძლებელი.' },
    consequence: { ka: 'ასტრონომიას ახალი „გრძნობის ორგანო" გაუჩნდა: ახლა სამყაროს არა მხოლოდ ვხედავთ, არამედ „ვისმენთ".' },
    topicIds: ['black-holes', 'relativity'],
    sources: [
      {
        label: 'Abbott et al., "Observation of Gravitational Waves from a Binary Black Hole Merger", PRL 116',
        publisher: 'Physical Review Letters',
        url: 'https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.116.061102',
        year: 2016,
        kind: 'journal',
      },
    ],
  },
  {
    id: 'e-eht-image',
    subjectId: 'astronomy',
    title: { ka: 'გამოქვეყნდა შავი ხვრელის პირველი გამოსახულება' },
    year: 2019,
    month: 4,
    day: 10,
    region: 'science',
    summary: {
      ka: 'Event Horizon Telescope-ის კოლაბორაციამ M87 გალაქტიკის ცენტრში მდებარე ზემასიური შავი ხვრელის სურათი წარადგინა.',
    },
    consequence: { ka: '2022 წელს იმავე მეთოდით მიიღეს ჩვენივე გალაქტიკის ცენტრში მდებარე Sagittarius A*-ის გამოსახულება.' },
    topicIds: ['black-holes'],
    sources: [
      {
        label: 'First M87 Event Horizon Telescope Results, ApJL 875 L1',
        publisher: 'Event Horizon Telescope Collaboration',
        url: 'https://iopscience.iop.org/article/10.3847/2041-8213/ab0ec7',
        year: 2019,
        kind: 'journal',
      },
    ],
  },
  {
    id: 'e-jwst-launch',
    subjectId: 'astronomy',
    title: { ka: 'გაუშვეს ჯეიმზ ვების კოსმოსური ტელესკოპი' },
    year: 2021,
    month: 12,
    day: 25,
    region: 'science',
    summary: {
      ka: 'ტელესკოპი Ariane 5 რაკეტით გაუშვეს. კოსმოსში მას 344 კრიტიკული ოპერაციის ავტომატურად შესრულება მოუწია — ნებისმიერი შეცდომა გამოუსწორებელი იქნებოდა.',
    },
    consequence: { ka: 'ვები დედამიწიდან 1.5 მილიონი კილომეტრით შორსაა და, ჰაბლისგან განსხვავებით, მისი შეკეთება ვერ მოხერხდება.' },
    sources: [nasa('James Webb Space Telescope', 'https://science.nasa.gov/mission/webb/')],
  },
  {
    id: 'e-alphago',
    subjectId: 'ai',
    title: { ka: 'AlphaGo-მ გოს მსოფლიო ჩემპიონი დაამარცხა' },
    year: 2016,
    month: 3,
    day: 15,
    region: 'science',
    summary: {
      ka: 'DeepMind-ის სისტემამ ლი სედოლი ხუთმატჩიან სერიაში 4:1 დაამარცხა. გო დიდი ხნის განმავლობაში ითვლებოდა თამაშად, სადაც მანქანა ადამიანს ვერ აჯობებდა.',
    },
    consequence: { ka: 'მეორე პარტიის 37-ე სვლა პროფესიონალებმა თავიდან შეცდომად მიიჩნიეს — შემდეგ კი აღიარეს, რომ ის ახალი სტრატეგიული იდეა იყო.' },
    sources: [
      {
        label: 'Silver et al., "Mastering the game of Go with deep neural networks and tree search", Nature 529',
        publisher: 'Nature',
        url: 'https://www.nature.com/articles/nature16961',
        year: 2016,
        kind: 'journal',
      },
    ],
  },
  {
    id: 'e-alphafold',
    subjectId: 'biology',
    title: { ka: 'AlphaFold-მა ცილის დაკეცვის ამოცანაში გარღვევა მოახდინა' },
    year: 2020,
    month: 11,
    day: 30,
    region: 'science',
    summary: {
      ka: 'CASP14-ის შეფასებაზე AlphaFold 2-მა ცილების სივრცული სტრუქტურა ექსპერიმენტულთან შესადარებელი სიზუსტით იწინასწარმეტყველა.',
    },
    cause: { ka: 'ცილის ფორმის დადგენას ლაბორატორიაში ხშირად წლები სჭირდებოდა — ეს ბიოლოგიის 50-წლიანი ღია პრობლემა იყო.' },
    consequence: { ka: 'პროგნოზირებული სტრუქტურების ბაზა საჯაროდ გამოქვეყნდა და დღეს მილიონობით ცილას მოიცავს.' },
    topicIds: ['proteins', 'dna'],
    sources: [
      {
        label: 'Jumper et al., "Highly accurate protein structure prediction with AlphaFold", Nature 596',
        publisher: 'Nature',
        url: 'https://www.nature.com/articles/s41586-021-03819-2',
        year: 2021,
        kind: 'journal',
      },
    ],
  },
  {
    id: 'e-turing-paper',
    subjectId: 'cs',
    title: { ka: 'ტიურინგმა გამოაქვეყნა ნაშრომი გამოთვლად რიცხვებზე' },
    year: 1936,
    month: 11,
    day: 30,
    region: 'science',
    summary: {
      ka: 'ნაშრომში „On Computable Numbers" აღწერილია აბსტრაქტული მანქანა და დამტკიცებულია, რომ არსებობს ამოცანები, რომელთა ალგორითმული ამოხსნაც შეუძლებელია.',
    },
    consequence: { ka: 'ეს გახდა თეორიული ინფორმატიკის საფუძველი — კომპიუტერების ფიზიკურად აგებამდე ათი წლით ადრე.' },
    topicIds: ['computability'],
    sources: [brit('Alan Turing', 'biography/Alan-Turing')],
  },
  {
    id: 'e-shannon-paper',
    subjectId: 'cs',
    title: { ka: 'შენონმა შექმნა ინფორმაციის თეორია' },
    year: 1948,
    month: 7,
    day: 1,
    region: 'science',
    summary: {
      ka: 'ნაშრომმა „A Mathematical Theory of Communication" შემოიღო ბიტი როგორც ინფორმაციის ერთეული და დაადგინა არხის გამტარუნარიანობის ზღვარი.',
    },
    consequence: { ka: 'ყოველი მოდემი, ყოველი შეკუმშვის ალგორითმი და ყოველი შეცდომის მაკორექტირებელი კოდი ამ თეორიას ეყრდნობა.' },
    topicIds: ['information-theory'],
    sources: [brit('Claude Shannon', 'biography/Claude-Shannon')],
  },
  {
    id: 'e-transistor',
    subjectId: 'electronics',
    title: { ka: 'შეიქმნა პირველი ტრანზისტორი' },
    year: 1947,
    month: 12,
    day: 23,
    region: 'science',
    summary: {
      ka: 'ბელის ლაბორატორიაში ბარდინმა, ბრატეინმა და შოკლიმ აჩვენეს ნახევარგამტარული მოწყობილობა, რომელსაც სიგნალის გაძლიერება შეეძლო.',
    },
    consequence: { ka: 'ტრანზისტორმა ჩაანაცვლა მოცულობითი და მყიფე ელექტრონული ლამპები. დღეს ერთ ჩიპზე მილიარდობით ტრანზისტორია.' },
    topicIds: ['computing-history'],
    sources: [brit('Transistor', 'technology/transistor')],
  },
  {
    id: 'e-wright',
    subjectId: 'engineering',
    title: { ka: 'ძმებმა რაიტებმა პირველი მართვადი ფრენა შეასრულეს' },
    year: 1903,
    month: 12,
    day: 17,
    region: 'science',
    summary: {
      ka: 'კიტი-ჰოკში პირველი ფრენა 12 წამი გაგრძელდა და 37 მეტრი დაფარა. იმავე დღეს კიდევ სამი ფრენა შესრულდა.',
    },
    cause: { ka: 'მათი მთავარი წვლილი ძრავა კი არ იყო, არამედ მართვის სისტემა — მანამდე არავის ჰქონდა გადაწყვეტილი, როგორ უნდა ემართა პილოტს აპარატი ჰაერში.' },
    sources: [
      {
        label: 'The Wright Brothers — The Invention of the Aerial Age',
        publisher: 'Smithsonian National Air and Space Museum',
        url: 'https://airandspace.si.edu/explore/stories/wright-brothers',
        kind: 'museum',
      },
    ],
  },
  {
    id: 'e-penicillin',
    subjectId: 'biology',
    title: { ka: 'ფლემინგმა პენიცილინი აღმოაჩინა' },
    year: 1928,
    month: 9,
    day: 28,
    region: 'science',
    summary: {
      ka: 'შვებულებიდან დაბრუნებულმა ფლემინგმა შენიშნა, რომ ბაქტერიების კულტურაში მოხვედრილი ობის გარშემო ბაქტერიები დაღუპულიყვნენ.',
    },
    consequence: { ka: 'ანტიბიოტიკების ეპოქა დაიწყო. დღეს მთავარი გამოწვევა ანტიბიოტიკებისადმი რეზისტენტობაა.' },
    sources: [brit('Alexander Fleming', 'biography/Alexander-Fleming')],
  },
  {
    id: 'e-printing',
    subjectId: 'history',
    title: { ka: 'გუტენბერგმა ევროპაში ასოთამწყობი სტამბა დანერგა' },
    year: 1455,
    region: 'world',
    summary: {
      ka: 'გუტენბერგის ბიბლია ევროპაში მოძრავი ლითონის ასოებით დაბეჭდილი პირველი მნიშვნელოვანი წიგნია. ზუსტი თარიღი უცნობია — დაბეჭდვა 1450-იანი წლების შუა ხანებით თარიღდება.',
    },
    consequence: { ka: '1500 წლისთვის ევროპაში უკვე მილიონობით ნაბეჭდი წიგნი იყო. ცოდნის გავრცელების სიჩქარემ თვისებრივად იცვალა სახე.' },
    topicIds: ['printing-revolution'],
    sources: [brit('Gutenberg Bible', 'topic/Gutenberg-Bible')],
  },

  /* ---------------- საქართველოს ისტორია ---------------- */
  {
    id: 'e-didgori',
    subjectId: 'georgian-history',
    title: { ka: 'დიდგორის ბრძოლა' },
    year: 1121,
    month: 8,
    day: 12,
    region: 'georgia',
    summary: {
      ka: 'დავით IV აღმაშენებლის ლაშქარმა დიდგორთან სელჩუკთა კოალიციური ჯარი დაამარცხა — მიუხედავად რიცხობრივი უპირატესობისა მოწინააღმდეგის მხარეს.',
    },
    cause: { ka: 'დავითის სამხედრო რეფორმებმა და ყივჩაღთა ჩამოსახლებამ საქართველოს მუდმივი, გაწვრთნილი ჯარი შეუქმნა.' },
    consequence: { ka: 'მომდევნო წელს გათავისუფლდა თბილისი და ის სამეფოს დედაქალაქი გახდა. დაიწყო საქართველოს „ოქროს ხანა".' },
    sources: [brit('Georgia — history', 'place/Georgia/History')],
  },
  {
    id: 'e-tamar',
    subjectId: 'georgian-history',
    title: { ka: 'თამარი საქართველოს მეფე გახდა' },
    year: 1184,
    region: 'georgia',
    summary: {
      ka: 'თამარი ჯერ მამის, გიორგი III-ის სიცოცხლეშივე დაისვა თანამოსაყდრედ, ხოლო 1184 წელს დამოუკიდებლად აღიმაღლა ტახტზე.',
    },
    consequence: { ka: 'მისი მეფობა საქართველოს პოლიტიკური და კულტურული აღმავლობის მწვერვალად ითვლება. სწორედ ამ პერიოდში შეიქმნა „ვეფხისტყაოსანი".' },
    topicIds: ['vepkhistqaosani'],
    sources: [brit('Tamara', 'biography/Tamara-queen-of-Georgia')],
  },
  {
    id: 'e-georgievsk',
    subjectId: 'georgian-history',
    title: { ka: 'გეორგიევსკის ტრაქტატი' },
    year: 1783,
    month: 7,
    day: 24,
    region: 'georgia',
    summary: {
      ka: 'ერეკლე II-მ და რუსეთის იმპერიამ ხელი მოაწერეს ტრაქტატს, რომლითაც ქართლ-კახეთი რუსეთის მფარველობაში გადადიოდა შიდა ავტონომიის შენარჩუნებით.',
    },
    cause: { ka: 'სამეფო ირანისა და ოსმალეთის მუდმივი საფრთხის ქვეშ იმყოფებოდა და გარე მოკავშირეს ეძებდა.' },
    consequence: { ka: 'ტრაქტატის პირობები არ შესრულდა. 1801 წელს რუსეთმა ქართლ-კახეთის სამეფო გააუქმა და იმპერიას შეუერთა.' },
    sources: [brit('Georgia — history', 'place/Georgia/History')],
  },
  {
    id: 'e-1918-independence',
    subjectId: 'georgian-history',
    title: { ka: 'გამოცხადდა საქართველოს დამოუკიდებლობა' },
    year: 1918,
    month: 5,
    day: 26,
    region: 'georgia',
    summary: {
      ka: 'ეროვნულმა საბჭომ საქართველოს დემოკრატიული რესპუბლიკის დამოუკიდებლობის აქტი მიიღო.',
    },
    consequence: { ka: 'რესპუბლიკა სამ წელს იარსება. 1921 წლის თებერვალში წითელი არმია საქართველოში შემოვიდა.' },
    sources: [brit('Georgia — history', 'place/Georgia/History')],
  },
  {
    id: 'e-1921-occupation',
    subjectId: 'georgian-history',
    title: { ka: 'წითელი არმია თბილისში შევიდა' },
    year: 1921,
    month: 2,
    day: 25,
    region: 'georgia',
    summary: {
      ka: 'საბჭოთა რუსეთის შეიარაღებული შეჭრის შედეგად საქართველოს დემოკრატიულმა რესპუბლიკამ არსებობა შეწყვიტა.',
    },
    consequence: { ka: 'დაიწყო 70-წლიანი საბჭოთა პერიოდი. დამოუკიდებლობა 1991 წელს აღდგა.' },
    sources: [brit('Georgia — history', 'place/Georgia/History')],
  },
  {
    id: 'e-1978-language',
    subjectId: 'georgian-history',
    title: { ka: '14 აპრილის გამოსვლები ქართული ენის დასაცავად' },
    year: 1978,
    month: 4,
    day: 14,
    region: 'georgia',
    summary: {
      ka: 'ახალი კონსტიტუციის პროექტი ქართული ენის სახელმწიფო ენის სტატუსს აუქმებდა. მასობრივი მშვიდობიანი გამოსვლების შედეგად მუხლი შენარჩუნდა.',
    },
    consequence: { ka: '14 აპრილი დღეს ქართული ენის დღედაა აღიარებული.' },
    topicIds: ['georgian-script'],
    sources: [brit('Georgia — history', 'place/Georgia/History')],
  },
  {
    id: 'e-1991-independence',
    subjectId: 'georgian-history',
    title: { ka: 'აღდგა საქართველოს სახელმწიფოებრივი დამოუკიდებლობა' },
    year: 1991,
    month: 4,
    day: 9,
    region: 'georgia',
    summary: {
      ka: 'რეფერენდუმის შედეგების საფუძველზე უზენაესმა საბჭომ დამოუკიდებლობის აღდგენის აქტი მიიღო.',
    },
    cause: { ka: 'აქტს წინ უძღოდა 1989 წლის 9 აპრილის ტრაგედია თბილისში.' },
    sources: [brit('Georgia — history', 'place/Georgia/History')],
  },
  {
    id: 'e-dmanisi-discovery',
    subjectId: 'georgian-history',
    title: { ka: 'დმანისში ჰომინიდის ქალა აღმოაჩინეს' },
    year: 1991,
    region: 'georgia',
    summary: {
      ka: 'დმანისის არქეოლოგიურ ძეგლზე დაიწყო აღმოჩენების სერია, რომელმაც აჩვენა, რომ ჰომინიდები კავკასიაში დაახლოებით 1.8 მილიონი წლის წინ იმყოფებოდნენ.',
    },
    consequence: { ka: 'ეს აფრიკის გარეთ ჰომინიდების ერთ-ერთი უძველესი ცნობილი კვალია და ადამიანის განსახლების თარიღების გადახედვა გამოიწვია.' },
    sources: [
      {
        label: 'Lordkipanidze et al., "A Complete Skull from Dmanisi, Georgia", Science 342',
        publisher: 'Science',
        url: 'https://www.science.org/doi/10.1126/science.1238484',
        year: 2013,
        kind: 'journal',
      },
    ],
  },
  {
    id: 'e-georgian-alphabet-unesco',
    subjectId: 'georgian-history',
    title: { ka: 'ქართული ანბანი იუნესკოს სიაში შევიდა' },
    year: 2016,
    month: 11,
    day: 30,
    region: 'georgia',
    summary: {
      ka: 'ქართული დამწერლობის სამი სახეობის — ასომთავრულის, ნუსხურისა და მხედრულის — ცოცხალი კულტურა იუნესკოს არამატერიალური კულტურული მემკვიდრეობის სიაში აღირიცხა.',
    },
    topicIds: ['georgian-script'],
    sources: [
      {
        label: 'Living culture of three writing systems of the Georgian alphabet',
        publisher: 'UNESCO',
        url: 'https://ich.unesco.org/en/RL/living-culture-of-three-writing-systems-of-the-georgian-alphabet-01205',
        year: 2016,
        kind: 'institution',
      },
    ],
  },

  /* ---------------- მსოფლიო ისტორია ---------------- */
  {
    id: 'e-bastille',
    subjectId: 'history',
    title: { ka: 'ბასტილიის აღება' },
    year: 1789,
    month: 7,
    day: 14,
    region: 'world',
    summary: {
      ka: 'პარიზელებმა შეიარაღების მოპოვების მიზნით ბასტილიის ციხე აიღეს. ციხეში იმ დროს მხოლოდ შვიდი პატიმარი იმყოფებოდა.',
    },
    consequence: { ka: 'მოვლენა საფრანგეთის რევოლუციის სიმბოლოდ იქცა და დღემდე ეროვნულ დღესასწაულად აღინიშნება.' },
    sources: [brit('Bastille Day', 'topic/Bastille-Day')],
  },
  {
    id: 'e-columbus',
    subjectId: 'history',
    title: { ka: 'კოლუმბის ექსპედიცია ამერიკის კონტინენტს მიადგა' },
    year: 1492,
    month: 10,
    day: 12,
    region: 'world',
    summary: {
      ka: 'კოლუმბი ინდოეთისკენ მიმავალ დასავლურ გზას ეძებდა და კარიბის ზღვის კუნძულებს მიაღწია. ის სიცოცხლის ბოლომდე თვლიდა, რომ აზიაში იყო.',
    },
    consequence: { ka: 'დაიწყო კონტინენტთაშორისი გაცვლა — მცენარეების, ცხოველებისა და დაავადებების. ამერიკის მკვიდრი მოსახლეობისთვის ეს კატასტროფული შედეგებით დასრულდა.' },
    sources: [brit('Christopher Columbus', 'biography/Christopher-Columbus')],
  },
  {
    id: 'e-magna-carta',
    subjectId: 'civics',
    title: { ka: 'ხელი მოეწერა დიდ ქარტიას (Magna Carta)' },
    year: 1215,
    month: 6,
    day: 15,
    region: 'world',
    summary: {
      ka: 'ინგლისის მეფე იოანემ ბარონების ზეწოლით დოკუმენტს მოაწერა ხელი, რომელიც მეფის ძალაუფლებას კანონით ზღუდავდა.',
    },
    consequence: { ka: 'ქარტია გახდა იმ იდეის სიმბოლო, რომ ხელისუფალიც კანონს ექვემდებარება — ეს თანამედროვე კონსტიტუციონალიზმის ერთ-ერთი საწყისია.' },
    sources: [brit('Magna Carta', 'topic/Magna-Carta')],
  },
  {
    id: 'e-udhr',
    subjectId: 'civics',
    title: { ka: 'მიღებულ იქნა ადამიანის უფლებათა საყოველთაო დეკლარაცია' },
    year: 1948,
    month: 12,
    day: 10,
    region: 'world',
    summary: {
      ka: 'გაეროს გენერალურმა ასამბლეამ პარიზში მიიღო დოკუმენტი, რომელიც პირველად ჩამოაყალიბა უფლებები, რომლებიც ყველა ადამიანს ეკუთვნის.',
    },
    consequence: { ka: 'დეკლარაცია მსოფლიოში ყველაზე მეტ ენაზე თარგმნილი დოკუმენტია და ეროვნული კონსტიტუციების საფუძვლად იქცა.' },
    sources: [
      {
        label: 'Universal Declaration of Human Rights',
        publisher: 'United Nations',
        url: 'https://www.un.org/en/about-us/universal-declaration-of-human-rights',
        year: 1948,
        kind: 'institution',
      },
    ],
  },
  {
    id: 'e-berlin-wall',
    subjectId: 'history',
    title: { ka: 'ბერლინის კედელი გაიხსნა' },
    year: 1989,
    month: 11,
    day: 9,
    region: 'world',
    summary: {
      ka: 'აღმოსავლეთ გერმანიის ხელისუფლების განცხადების არასწორმა ინტერპრეტაციამ გამოიწვია ის, რომ იმავე ღამეს ათასობით ადამიანი საზღვარზე მივიდა და გამშვები პუნქტები გაიხსნა.',
    },
    consequence: { ka: 'ერთ წელიწადში გერმანია გაერთიანდა. მოვლენა ცივი ომის დასასრულის სიმბოლოდ იქცა.' },
    sources: [brit('Berlin Wall', 'topic/Berlin-Wall')],
  },

  /* ---------------- ინფორმატიკის ისტორია ---------------- */
  {
    id: 'e-dartmouth-ai',
    subjectId: 'ai',
    title: { ka: 'დარტმუთის სემინარმა შემოიღო ტერმინი „ხელოვნური ინტელექტი"' },
    year: 1956,
    region: 'science',
    summary: {
      ka: 'ჯონ მაკკარტიმ, მარვინ მინსკიმ და კოლეგებმა ერთი ზაფხული დაუთმეს კითხვას, შეიძლებოდა თუ არა მანქანას ენა ეხმარა, ცნებები ჩამოეყალიბებინა და ამოცანები ეამოხსნა. სწორედ განაცხადში გაჩნდა ტერმინი „artificial intelligence".',
    },
    consequence: { ka: 'სემინარი ითვლება AI-ის, როგორც ცალკე დარგის, დაბადებად. ადრეული ოპტიმიზმი მალევე შენელდა.' },
    topicIds: ['what-is-machine-learning', 'computing-history'],
    sources: [brit('Artificial intelligence', 'technology/artificial-intelligence')],
  },
  {
    id: 'e-fortran',
    subjectId: 'programming',
    title: { ka: 'IBM-მა გამოუშვა FORTRAN — პირველი ფართოდ გავრცელებული მაღალი დონის ენა' },
    year: 1957,
    region: 'science',
    summary: {
      ka: 'FORTRAN-მა პროგრამისტს საშუალება მისცა, ფორმულები თითქმის მათემატიკური სახით დაეწერა, მანქანური კოდის ნაცვლად. ბევრი ეჭვობდა, რომ ავტომატური მთარგმნელი ადამიანივით კარგ კოდს დაწერდა.',
    },
    consequence: { ka: 'კომპილატორმა ეს ეჭვი გააქარწყლა და გზა გაუხსნა ასობით ენას, რომლებმაც პროგრამირება ფართო წრისთვის ხელმისაწვდომი გახადა.' },
    topicIds: ['how-code-runs', 'computing-history'],
    sources: [brit('FORTRAN', 'technology/FORTRAN')],
  },
  {
    id: 'e-lisp',
    subjectId: 'programming',
    title: { ka: 'ჯონ მაკკარტიმ შექმნა Lisp' },
    year: 1958,
    region: 'science',
    summary: {
      ka: 'Lisp-ში პროგრამა და მონაცემი ერთი ფორმისაა, რეკურსია ენის გულია, მეხსიერებას კი ავტომატურად ალაგებს „ნაგვის შემგროვებელი". ეს იდეები რადიკალური იყო თავის დროზე.',
    },
    consequence: { ka: 'Lisp-ის ცნებები — პირველი კლასის ფუნქციები, ავტომატური მეხსიერება, დინამიკური ტიპები — დღეს თითქმის ყველა თანამედროვე ენაშია.' },
    topicIds: ['functions-and-abstraction', 'programming-paradigms', 'recursion'],
    sources: [brit('LISP', 'technology/LISP-computer-language')],
  },
  {
    id: 'e-quicksort',
    subjectId: 'algorithms',
    title: { ka: 'ტონი ჰოარმა გამოაქვეყნა Quicksort' },
    year: 1961,
    region: 'science',
    summary: {
      ka: 'ჰოარმა ალგორითმი 1959 წელს, მოსკოვში მთარგმნელობით პროექტზე მუშაობისას მოიფიქრა — რუსული სიტყვების დალაგების ამოცანაზე ფიქრისას. „გაყავი და იბატონე" პრინციპი მას საშუალოდ O(n log n) სისწრაფეს აძლევს.',
    },
    consequence: { ka: 'Quicksort დღემდე ერთ-ერთი ყველაზე გავრცელებული დალაგების ალგორითმია და სტანდარტული ბიბლიოთეკების საფუძველია.' },
    topicIds: ['sorting-algorithms', 'algorithm-complexity'],
    sources: [brit('Sorting algorithm', 'technology/sorting-algorithm')],
  },
  {
    id: 'e-dijkstra-algorithm',
    subjectId: 'algorithms',
    title: { ka: 'გამოქვეყნდა დაიქსტრას უმოკლესი გზის ალგორითმი' },
    year: 1959,
    region: 'science',
    summary: {
      ka: 'დაიქსტრამ ალგორითმი 1956 წელს კაფეში მოიფიქრა, გამოაქვეყნა კი 1959 წელს — სამგვერდიან სტატიაში. ის პოულობს უმოკლეს გზას გრაფში, სადაც წიბოებს არაუარყოფითი წონა აქვთ.',
    },
    consequence: { ka: 'ალგორითმი დღეს GPS-ნავიგაციის, ქსელური მარშრუტიზაციისა და ლოგისტიკის საფუძველია.' },
    topicIds: ['graphs-and-paths'],
    sources: [brit('Edsger Dijkstra', 'biography/Edsger-Dijkstra')],
  },
  {
    id: 'e-c-language',
    subjectId: 'programming',
    title: { ka: 'დენის რიჩიმ შექმნა ენა C' },
    year: 1972,
    region: 'science',
    summary: {
      ka: 'Bell Labs-ში რიჩიმ შექმნა ენა, რომელიც აპარატურასთან საკმარისად ახლოს იყო ოპერაციული სისტემის დასაწერად, მაგრამ საკმარისად პორტაბელური, რომ სხვა მანქანაზე გადატანილიყო. მალევე მასზე გადაიწერა Unix.',
    },
    consequence: { ka: 'C-ისა და Unix-ის შთამომავლები (Linux, macOS, Android) დღეს კომპიუტერების უმეტესობას ამუშავებს. C-ის სინტაქსი დღემდე ჩანს C++, Java, JavaScript-სა და სხვ.-ში.' },
    topicIds: ['how-code-runs', 'computing-history'],
    sources: [brit('C (programming language)', 'technology/C-computer-programming-language')],
  },
  {
    id: 'e-python',
    subjectId: 'programming',
    title: { ka: 'გამოვიდა Python-ის პირველი ვერსია' },
    year: 1991,
    month: 2,
    region: 'science',
    summary: {
      ka: 'გვიდო ვან როსუმმა გამოუშვა ენა, რომელიც წაკითხვადობას აყენებდა პირველ ადგილზე: ბლოკები აისახება შეწევით, სინტაქსი კი მინიმალურია. ენა კომედიური ჯგუფის „Monty Python"-ის სახელით დაერქვა.',
    },
    consequence: { ka: 'Python გახდა მეცნიერების, მონაცემთა ანალიზისა და მანქანური სწავლების დომინანტი ენა და ერთ-ერთი ყველაზე გავრცელებული პირველი ენა სწავლისთვის.' },
    topicIds: ['how-code-runs'],
    sources: [brit('Python (computer language)', 'technology/Python-computer-language')],
  },
  {
    id: 'e-git',
    subjectId: 'programming',
    title: { ka: 'ლინუს ტორვალდსმა შექმნა Git' },
    year: 2005,
    month: 4,
    day: 7,
    region: 'science',
    summary: {
      ka: 'როცა Linux-ის გუნდმა დაკარგა უფასო წვდომა ვერსიების კონტროლის სისტემა BitKeeper-ზე, ტორვალდსმა ორ კვირაში დაწერა ახალი: სწრაფი, განაწილებული და კრიპტოგრაფიულად დამოწმებული ისტორიით.',
    },
    consequence: { ka: 'Git გახდა ვერსიების კონტროლის დე-ფაქტო სტანდარტი და ღია კოდის მასშტაბური თანამშრომლობის საფუძველი (GitHub, GitLab).' },
    topicIds: ['version-control', 'computing-history'],
    sources: [brit('Linus Torvalds', 'biography/Linus-Torvalds')],
  },
  {
    id: 'e-imagenet-alexnet',
    subjectId: 'ai',
    title: { ka: 'ღრმა ნეირონულმა ქსელმა (AlexNet) მოიგო ImageNet-ის კონკურსი' },
    year: 2012,
    region: 'science',
    summary: {
      ka: 'ჯეფრი ჰინტონის სტუდენტების — კრიჟევსკისა და სუცკევერის — ქსელმა სურათების ამოცნობაში დანარჩენ მიდგომებს იმდენად ჯობნა, რომ შედეგი ცალკე გამონაკლისად აღიქმებოდა. სწავლა GPU-ებზე შესრულდა.',
    },
    consequence: { ka: 'ღრმა სწავლება ერთ წელიწადში კვლევის მთავარ მიმართულებად იქცა — მხედველობა, თარგმანი, მეტყველება ერთმანეთის მიყოლებით „დაიპყრო".' },
    topicIds: ['neural-networks', 'what-is-machine-learning'],
    sources: [
      {
        label: 'ImageNet Classification with Deep Convolutional Neural Networks',
        publisher: 'NeurIPS',
        url: 'https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks',
        year: 2012,
        kind: 'journal',
      },
    ],
  },
  {
    id: 'e-transformer',
    subjectId: 'ai',
    title: { ka: 'გამოქვეყნდა ნაშრომი „Attention Is All You Need"' },
    year: 2017,
    month: 6,
    day: 12,
    region: 'science',
    summary: {
      ka: 'Google-ის რვა მკვლევარმა აღწერა „ტრანსფორმერის" არქიტექტურა, რომელმაც თანმიმდევრული დამუშავება მთლიანად ჩაანაცვლა „ყურადღების" მექანიზმით: ყოველი სიტყვა ერთდროულად ხედავს ყველა სხვას.',
    },
    consequence: { ka: 'ტრანსფორმერი გახდა ყველა თანამედროვე დიდი ენობრივი მოდელის (GPT, Claude, Gemini) საფუძველი.' },
    topicIds: ['large-language-models', 'neural-networks'],
    sources: [
      {
        label: 'Attention Is All You Need',
        publisher: 'arXiv',
        url: 'https://arxiv.org/abs/1706.03762',
        year: 2017,
        kind: 'journal',
      },
    ],
  },

  /* ---------------- საქართველოს ისტორია ---------------- */
  {
    id: 'e-didgori',
    subjectId: 'georgian-history',
    title: { ka: 'დიდგორის ბრძოლა — „ძლევაი საკვირველი"' },
    year: 1121,
    month: 8,
    day: 12,
    region: 'georgia',
    summary: {
      ka: 'დავით IV აღმაშენებლის დაახლოებით 55 000-კაციანმა ლაშქარმა დიდგორთან დაამარცხა გაცილებით მრავალრიცხოვანი სელჩუკური კოალიცია.',
    },
    cause: { ka: 'სელჩუკები ყოველწლიურად არბევდნენ საქართველოს; დავითმა ჯერ არმია და სახელმწიფო გააძლიერა, მერე ღია ბრძოლა მიიღო.' },
    consequence: { ka: 'მომდევნო წელს გათავისუფლდა თბილისი და დედაქალაქად გამოცხადდა. დაიწყო „ოქროს ხანა".' },
    topicIds: ['georgian-golden-age'],
    sources: [brit('Battle of Didgori', 'event/Battle-of-Didgori')],
  },
  {
    id: 'e-tbilisi-1795',
    subjectId: 'georgian-history',
    title: { ka: 'კრწანისის ბრძოლა და თბილისის აოხრება' },
    year: 1795,
    month: 9,
    region: 'georgia',
    summary: {
      ka: 'სპარსეთის მმართველმა აღა-მაჰმად-ხანმა კრწანისთან დაამარცხა ერეკლე II-ის მცირერიცხოვანი ჯარი და თბილისი გადაწვა.',
    },
    cause: { ka: 'ერეკლე II-მ 1783 წელს რუსეთთან დადო გეორგიევსკის ტრაქტატი; სპარსეთმა ეს დამოუკიდებლობის დარღვევად მიიჩნია.' },
    consequence: { ka: 'რუსული სამხედრო დახმარება არ მოვიდა. ეს კატასტროფა 1801 წლის რუსული ანექსიის ერთ-ერთი უშუალო წინაპირობა გახდა.' },
    topicIds: ['georgian-fragmentation'],
    sources: [brit('Georgia — History', 'place/Georgia/History')],
  },
  {
    id: 'e-georgia-1918',
    subjectId: 'georgian-history',
    title: { ka: 'გამოცხადდა საქართველოს დემოკრატიული რესპუბლიკა' },
    year: 1918,
    month: 5,
    day: 26,
    region: 'georgia',
    summary: {
      ka: 'რუსეთის იმპერიის დაშლის ფონზე ეროვნულმა საბჭომ გამოაცხადა დამოუკიდებელი საქართველო სოციალ-დემოკრატიული მთავრობით.',
    },
    consequence: { ka: 'სამწლიან რესპუბლიკაში ქალებმა ხმის უფლება მიიღეს; 1921 წლის აქტი და 1991 წლის დამოუკიდებლობა სწორედ ამ თარიღს ეყრდნობა.' },
    topicIds: ['first-republic-1918'],
    sources: [brit('Georgia — Independence', 'place/Georgia/History')],
  },
  {
    id: 'e-georgia-1921',
    subjectId: 'georgian-history',
    title: { ka: 'წითელი არმიის შემოსევა და საქართველოს გასაბჭოება' },
    year: 1921,
    month: 2,
    day: 25,
    region: 'georgia',
    summary: {
      ka: 'თითქმის წლით ადრე დადებული სამშვიდობო ხელშეკრულების მიუხედავად, საბჭოთა რუსეთის წითელი არმია საქართველოში შემოიჭრა; 25 თებერვალს დაეცა თბილისი.',
    },
    cause: { ka: 'საქართველოს სტრატეგიული მდებარეობა და ბაქოს ნავთობის მარშრუტი; საბჭოთა კავშირის მიზანი — კავკასიის კონტროლი.' },
    consequence: { ka: 'მთავრობა ემიგრაციაში გადავიდა. 70-წლიანი საბჭოთა პერიოდი დაიწყო. 1924 წლის აჯანყება სისხლში ჩაახშეს.' },
    topicIds: ['first-republic-1918', 'soviet-georgia-independence'],
    sources: [brit('Georgia — The Soviet period', 'place/Georgia/History')],
  },
  {
    id: 'e-april-9-1989',
    subjectId: 'georgian-history',
    title: { ka: '9 აპრილის ტრაგედია' },
    year: 1989,
    month: 4,
    day: 9,
    region: 'georgia',
    summary: {
      ka: 'თბილისში, სამთავრობო შენობის წინ მშვიდობიანი აქცია საბჭოთა ჯარმა ძალის გამოყენებით დაშალა. დაიღუპა 21 ადამიანი, უმეტესობა ქალი.',
    },
    consequence: { ka: 'მოვლენამ ქართული საზოგადოება საბოლოოდ მოწყვიტა საბჭოთა კავშირს. ზუსტად ორი წლის შემდეგ, 9 აპრილს, გამოცხადდა დამოუკიდებლობა.' },
    topicIds: ['soviet-georgia-independence'],
    sources: [
      {
        label: '9 აპრილის ტრაგედია',
        publisher: 'საქართველოს პარლამენტის ეროვნული ბიბლიოთეკა',
        url: 'http://www.nplg.gov.ge/',
        kind: 'institution',
      },
    ],
  },
  {
    id: 'e-georgia-1991',
    subjectId: 'georgian-history',
    title: { ka: 'საქართველოს სახელმწიფოებრივი დამოუკიდებლობის აღდგენა' },
    year: 1991,
    month: 4,
    day: 9,
    region: 'georgia',
    summary: {
      ka: '31 მარტის რეფერენდუმის საფუძველზე (98%-ზე მეტი მხარდაჭერით) უზენაესმა საბჭომ მიიღო დამოუკიდებლობის აღდგენის აქტი, რომელიც 1918 წლის 26 მაისს ეყრდნობოდა.',
    },
    consequence: { ka: 'დამოუკიდებლობას მოჰყვა მძიმე გარდამავალი პერიოდი: სამოქალაქო დაპირისპირება, კონფლიქტები და ეკონომიკური კოლაფსი 1990-იანების შუამდე.' },
    topicIds: ['soviet-georgia-independence'],
    sources: [
      {
        label: 'Act of Restoration of State Independence of Georgia (1991)',
        publisher: 'საქართველოს საკანონმდებლო მაცნე',
        url: 'https://matsne.gov.ge/en/document/view/32362',
        kind: 'institution',
      },
    ],
  },
];
