import type { Formula } from './schema';

const S = {
  hyperphysics: {
    label: 'HyperPhysics',
    publisher: 'Georgia State University',
    url: 'http://hyperphysics.phy-astr.gsu.edu/hbase/index.html',
    kind: 'institution' as const,
  },
  nist: {
    label: 'CODATA Internationally Recommended Values',
    publisher: 'NIST',
    url: 'https://physics.nist.gov/cuu/Constants/',
    kind: 'institution' as const,
  },
  iupac: {
    label: 'IUPAC Gold Book',
    publisher: 'IUPAC',
    url: 'https://goldbook.iupac.org/',
    kind: 'institution' as const,
  },
};

export const FORMULAS: Formula[] = [
  /* ===================== მათემატიკა ===================== */
  {
    id: 'quadratic',
    subjectId: 'algebra',
    name: { ka: 'კვადრატული განტოლების ფესვები', en: 'Quadratic formula' },
    expression: 'x = (−b ± √(b² − 4ac)) / 2a',
    variables: [
      { symbol: 'a', meaning: { ka: 'კოეფიციენტი x²-თან; a ≠ 0' } },
      { symbol: 'b', meaning: { ka: 'კოეფიციენტი x-თან' } },
      { symbol: 'c', meaning: { ka: 'თავისუფალი წევრი' } },
      { symbol: 'b² − 4ac', meaning: { ka: 'დისკრიმინანტი — ის წყვეტს, რამდენი ფესვია' } },
    ],
    explanation: {
      ka: 'ნებისმიერი ax² + bx + c = 0 ფორმის განტოლების ამოხსნა. მთავარი აქ დისკრიმინანტია: თუ ის დადებითია, პარაბოლა ღერძს ორ წერტილში კვეთს; თუ ნულია — ეხება; თუ უარყოფითია — საერთოდ არ კვეთს და ნამდვილ ფესვებს ვერ ვიპოვით.',
    },
    example: {
      ka: 'x² − 5x + 6 = 0 → დისკრიმინანტი = 25 − 24 = 1 → x = (5 ± 1)/2 → x₁ = 3, x₂ = 2.',
    },
    category: 'mathematics',
    difficulty: 2,
    relatedFormulaIds: ['vieta', 'parabola-vertex'],
    topicIds: ['quadratic-equations'],
  },
  {
    id: 'vieta',
    subjectId: 'algebra',
    name: { ka: 'ვიეტის თეორემა' },
    expression: 'x₁ + x₂ = −b/a,  x₁ · x₂ = c/a',
    variables: [
      { symbol: 'x₁, x₂', meaning: { ka: 'კვადრატული განტოლების ფესვები' } },
      { symbol: 'a, b, c', meaning: { ka: 'განტოლების კოეფიციენტები' } },
    ],
    explanation: {
      ka: 'ფესვების ჯამი და ნამრავლი პირდაპირ კოეფიციენტებიდან ჩანს — თვითონ ფესვების პოვნის გარეშე. ხშირად ამით უფრო სწრაფად ხსნი ამოცანას, ვიდრე დისკრიმინანტით.',
    },
    example: { ka: 'x² − 5x + 6 = 0 → ჯამი = 5, ნამრავლი = 6 → რიცხვები 2 და 3.' },
    category: 'mathematics',
    difficulty: 2,
    relatedFormulaIds: ['quadratic'],
    topicIds: ['quadratic-equations'],
  },
  {
    id: 'parabola-vertex',
    subjectId: 'algebra',
    name: { ka: 'პარაბოლის წვერო' },
    expression: 'x₀ = −b / 2a',
    variables: [
      { symbol: 'x₀', meaning: { ka: 'წვეროს აბსცისა — მინიმუმის ან მაქსიმუმის წერტილი' } },
    ],
    explanation: {
      ka: 'პარაბოლა სიმეტრიულია და მისი ღერძი ზუსტად ფესვებს შორის შუაშია. სწორედ აქ აღწევს ფუნქცია უმცირეს (a > 0) ან უდიდეს (a < 0) მნიშვნელობას.',
    },
    category: 'mathematics',
    difficulty: 2,
    relatedFormulaIds: ['quadratic'],
    topicIds: ['quadratic-equations'],
  },
  {
    id: 'pythagoras',
    subjectId: 'geometry',
    name: { ka: 'პითაგორას თეორემა' },
    expression: 'a² + b² = c²',
    variables: [
      { symbol: 'a, b', meaning: { ka: 'მართკუთხა სამკუთხედის კათეტები' }, unit: 'm' },
      { symbol: 'c', meaning: { ka: 'ჰიპოტენუზა — მართი კუთხის მოპირდაპირე გვერდი' }, unit: 'm' },
    ],
    explanation: {
      ka: 'მხოლოდ მართკუთხა სამკუთხედისთვის მუშაობს. სწორედ ეს თეორემა განსაზღვრავს, რას ნიშნავს „მანძილი" ბრტყელ სივრცეში — კოორდინატებში მანძილის ფორმულა პირდაპირ აქედან გამომდინარეობს.',
    },
    example: { ka: 'კათეტები 3 და 4 → c = √(9 + 16) = 5. ეს ცნობილი 3-4-5 სამკუთხედია, რომელსაც მშენებლები დღემდე იყენებენ მართი კუთხის შესამოწმებლად.' },
    category: 'mathematics',
    difficulty: 1,
    relatedFormulaIds: ['distance-2d', 'cosine-rule'],
    topicIds: ['pythagorean-theorem'],
  },
  {
    id: 'distance-2d',
    subjectId: 'geometry',
    name: { ka: 'მანძილი ორ წერტილს შორის' },
    expression: 'd = √((x₂ − x₁)² + (y₂ − y₁)²)',
    variables: [
      { symbol: 'd', meaning: { ka: 'მანძილი' }, unit: 'm' },
      { symbol: '(x₁, y₁), (x₂, y₂)', meaning: { ka: 'ორი წერტილის კოორდინატები' } },
    ],
    explanation: {
      ka: 'ეს იგივე პითაგორას თეორემაა, უბრალოდ კოორდინატულ ბადეზე გადატანილი: კათეტებია კოორდინატთა სხვაობები.',
    },
    category: 'mathematics',
    difficulty: 2,
    relatedFormulaIds: ['pythagoras'],
  },
  {
    id: 'circle-area',
    subjectId: 'geometry',
    name: { ka: 'წრის ფართობი' },
    expression: 'A = πr²',
    variables: [
      { symbol: 'A', meaning: { ka: 'ფართობი' }, unit: 'm²' },
      { symbol: 'r', meaning: { ka: 'რადიუსი' }, unit: 'm' },
      { symbol: 'π', meaning: { ka: 'წრეწირის სიგრძის შეფარდება დიამეტრთან ≈ 3.14159' } },
    ],
    explanation: {
      ka: 'რადიუსის გაორმაგება ფართობს ოთხჯერ ზრდის, არა ორჯერ — რადგან r კვადრატშია. სწორედ ამიტომ არის დიდი ტელესკოპი შეუდარებლად უფრო ძლიერი, ვიდრე ორჯერ პატარა.',
    },
    example: { ka: 'r = 3 მ → A = π · 9 ≈ 28.3 მ².' },
    category: 'mathematics',
    difficulty: 1,
    relatedFormulaIds: ['sphere-volume', 'circle-circumference'],
    topicIds: ['pi'],
  },
  {
    id: 'circle-circumference',
    subjectId: 'geometry',
    name: { ka: 'წრეწირის სიგრძე' },
    expression: 'C = 2πr',
    variables: [
      { symbol: 'C', meaning: { ka: 'წრეწირის სიგრძე' }, unit: 'm' },
      { symbol: 'r', meaning: { ka: 'რადიუსი' }, unit: 'm' },
    ],
    explanation: {
      ka: 'რაც არ უნდა დიდი ან პატარა იყოს წრე, სიგრძის შეფარდება დიამეტრთან ყოველთვის ერთი და იგივე რიცხვია — π. ეს თავისთავად აშკარა არ არის და სწორედ ამიტომ არის π ასეთი განსაკუთრებული.',
    },
    category: 'mathematics',
    difficulty: 1,
    relatedFormulaIds: ['circle-area'],
    topicIds: ['pi'],
  },
  {
    id: 'sphere-volume',
    subjectId: 'geometry',
    name: { ka: 'სფეროს მოცულობა' },
    expression: 'V = (4/3)πr³',
    variables: [
      { symbol: 'V', meaning: { ka: 'მოცულობა' }, unit: 'm³' },
      { symbol: 'r', meaning: { ka: 'რადიუსი' }, unit: 'm' },
    ],
    explanation: {
      ka: 'არქიმედემ დაამტკიცა, რომ სფეროს მოცულობა მისი შემომწერი ცილინდრის მოცულობის ზუსტად ორი მესამედია. ის ამ აღმოჩენით იმდენად ამაყობდა, რომ საფლავზე სფერო და ცილინდრი გამოაკვეთინა.',
    },
    category: 'mathematics',
    difficulty: 2,
    relatedFormulaIds: ['circle-area'],
  },
  {
    id: 'euler-identity',
    subjectId: 'math',
    name: { ka: 'ეილერის იგივეობა' },
    expression: 'e^(iπ) + 1 = 0',
    variables: [
      { symbol: 'e', meaning: { ka: 'ნატურალური ლოგარითმის ფუძე ≈ 2.71828' } },
      { symbol: 'i', meaning: { ka: 'წარმოსახვითი ერთეული, i² = −1' } },
      { symbol: 'π', meaning: { ka: 'წრის მუდმივა ≈ 3.14159' } },
    ],
    explanation: {
      ka: 'ხუთი ყველაზე მნიშვნელოვანი რიცხვი — 0, 1, π, e და i — ერთ მოკლე ტოლობაშია გაერთიანებული. ეს არ არის ხრიკი: ის ეილერის უფრო ზოგადი ფორმულის კერძო შემთხვევაა და გვიჩვენებს, რომ ჩვენება და ბრუნვა ერთი და იმავე მოვლენის ორი მხარეა.',
    },
    category: 'mathematics',
    difficulty: 4,
    relatedFormulaIds: ['eulers-formula'],
    topicIds: ['complex-numbers'],
  },
  {
    id: 'eulers-formula',
    subjectId: 'math',
    name: { ka: 'ეილერის ფორმულა' },
    expression: 'e^(ix) = cos x + i·sin x',
    variables: [{ symbol: 'x', meaning: { ka: 'კუთხე რადიანებში' }, unit: 'rad' }],
    explanation: {
      ka: 'ეს ფორმულა აკავშირებს მაჩვენებლიან ფუნქციას ტრიგონომეტრიასთან. პრაქტიკული აზრი: ბრუნვა კომპლექსურ სიბრტყეზე მარტივი გამრავლებით აღიწერება — სწორედ ამიტომ ეყრდნობა მას ელექტროტექნიკა და სიგნალების დამუშავება.',
    },
    category: 'mathematics',
    difficulty: 4,
    relatedFormulaIds: ['euler-identity'],
    topicIds: ['complex-numbers'],
  },
  {
    id: 'derivative-def',
    subjectId: 'calculus',
    name: { ka: 'წარმოებულის განსაზღვრება' },
    expression: "f′(x) = lim(h→0) [f(x + h) − f(x)] / h",
    variables: [
      { symbol: "f′(x)", meaning: { ka: 'ფუნქციის ცვლილების სიჩქარე x წერტილში' } },
      { symbol: 'h', meaning: { ka: 'უსასრულოდ მცირე ნაბიჯი' } },
    ],
    explanation: {
      ka: 'წარმოებული პასუხობს კითხვას: „რამდენად სწრაფად იცვლება ეს სიდიდე ზუსტად ამ წამს?" აზრი მარტივია — ვიღებთ ორ ახლო წერტილს შორის დახრილობას და შემდეგ მათ ერთმანეთს ვუახლოებთ, სანამ მანძილი პრაქტიკულად არ გაქრება.',
    },
    example: { ka: 'თუ f(x) = x², მაშინ f′(x) = 2x. ე.ი. x = 3-ზე ფუნქცია 6-ჯერ უფრო სწრაფად იზრდება, ვიდრე x.' },
    category: 'mathematics',
    difficulty: 3,
    relatedFormulaIds: ['power-rule', 'integral-power'],
    topicIds: ['derivatives'],
  },
  {
    id: 'power-rule',
    subjectId: 'calculus',
    name: { ka: 'ხარისხის წარმოებული' },
    expression: "(xⁿ)′ = n·xⁿ⁻¹",
    variables: [{ symbol: 'n', meaning: { ka: 'ხარისხის მაჩვენებელი' } }],
    explanation: {
      ka: 'ყველაზე ხშირად გამოყენებული წესი კალკულუსში: მაჩვენებელი ჩამოდის კოეფიციენტად და ერთით მცირდება.',
    },
    example: { ka: '(x⁵)′ = 5x⁴' },
    category: 'mathematics',
    difficulty: 3,
    relatedFormulaIds: ['derivative-def'],
    topicIds: ['derivatives'],
  },
  {
    id: 'integral-power',
    subjectId: 'calculus',
    name: { ka: 'ხარისხის ინტეგრალი' },
    expression: '∫xⁿ dx = xⁿ⁺¹/(n + 1) + C,  n ≠ −1',
    variables: [{ symbol: 'C', meaning: { ka: 'ინტეგრების მუდმივა' } }],
    explanation: {
      ka: 'ინტეგრება წარმოებულის შებრუნებული მოქმედებაა. C იმიტომ ჩნდება, რომ მუდმივას წარმოებული ნულია — ანუ უსასრულოდ ბევრი ფუნქციას აქვს ერთი და იგივე წარმოებული.',
    },
    category: 'mathematics',
    difficulty: 3,
    relatedFormulaIds: ['power-rule'],
    topicIds: ['derivatives'],
  },
  {
    id: 'geometric-sum',
    subjectId: 'algebra',
    name: { ka: 'გეომეტრიული პროგრესიის ჯამი' },
    expression: 'Sₙ = a₁(1 − qⁿ) / (1 − q),  q ≠ 1',
    variables: [
      { symbol: 'a₁', meaning: { ka: 'პირველი წევრი' } },
      { symbol: 'q', meaning: { ka: 'მამრავლი — რამდენჯერ იზრდება ყოველი შემდეგი წევრი' } },
      { symbol: 'n', meaning: { ka: 'წევრების რაოდენობა' } },
    ],
    explanation: {
      ka: 'თუ |q| < 1, უსასრულო ჯამიც კი სასრულია: S = a₁/(1 − q). სწორედ ამიტომ „უსასრულოდ ბევრი ნაწილის" შეკრება ყოველთვის უსასრულობას არ იძლევა — ეს ზენონის აპორიების პასუხია.',
    },
    example: { ka: '1 + ½ + ¼ + ⅛ + … = 1/(1 − ½) = 2.' },
    category: 'mathematics',
    difficulty: 3,
    relatedFormulaIds: ['arithmetic-sum'],
    topicIds: ['infinity'],
  },
  {
    id: 'arithmetic-sum',
    subjectId: 'algebra',
    name: { ka: 'არითმეტიკული პროგრესიის ჯამი' },
    expression: 'Sₙ = n(a₁ + aₙ) / 2',
    variables: [
      { symbol: 'a₁, aₙ', meaning: { ka: 'პირველი და ბოლო წევრი' } },
      { symbol: 'n', meaning: { ka: 'წევრების რაოდენობა' } },
    ],
    explanation: {
      ka: 'ლეგენდის თანახმად, ამ ხრიკი პატარა გაუსმა გამოიგონა, როცა მასწავლებელმა 1-დან 100-მდე შეკრება დაავალა: წყვილებად აჯგუფებ ბოლოებს — 1+100, 2+99 … — და ყოველი წყვილის ჯამი ერთნაირია.',
    },
    example: { ka: '1 + 2 + … + 100 = 100 · 101 / 2 = 5050.' },
    category: 'mathematics',
    difficulty: 2,
    relatedFormulaIds: ['geometric-sum'],
  },
  {
    id: 'combination',
    subjectId: 'probability',
    name: { ka: 'კომბინაციების რაოდენობა' },
    expression: 'C(n, k) = n! / (k!·(n − k)!)',
    variables: [
      { symbol: 'n', meaning: { ka: 'სულ რამდენი ობიექტია' } },
      { symbol: 'k', meaning: { ka: 'რამდენს ვირჩევთ' } },
      { symbol: '!', meaning: { ka: 'ფაქტორიალი: 5! = 5·4·3·2·1' } },
    ],
    explanation: {
      ka: 'რამდენი განსხვავებული ჯგუფის შედგენა შეიძლება, როცა თანმიმდევრობას მნიშვნელობა არ აქვს. მნიშვნელი სწორედ იმიტომ არის, რომ ერთი და იგივე ჯგუფის სხვადასხვა რიგით დათვლა არ მოხდეს.',
    },
    example: { ka: '5 მეგობრიდან 2-ის არჩევა: C(5,2) = 120 / (2 · 6) = 10 წყვილი.' },
    category: 'statistics',
    difficulty: 3,
    relatedFormulaIds: ['bayes'],
    topicIds: ['probability-basics'],
  },
  {
    id: 'sine-rule',
    subjectId: 'trigonometry',
    name: { ka: 'სინუსების თეორემა' },
    expression: 'a / sin A = b / sin B = c / sin C = 2R',
    variables: [
      { symbol: 'a, b, c', meaning: { ka: 'გვერდები' }, unit: 'm' },
      { symbol: 'A, B, C', meaning: { ka: 'მოპირდაპირე კუთხეები' }, unit: '°' },
      { symbol: 'R', meaning: { ka: 'შემომწერი წრეწირის რადიუსი' }, unit: 'm' },
    ],
    explanation: {
      ka: 'გვერდი და მისი მოპირდაპირე კუთხის სინუსი ერთმანეთის პროპორციულია. სწორედ ამით ზომავენ ასტრონომები ვარსკვლავებამდე მანძილს — ორი წერტილიდან იღებენ კუთხეს და დანარჩენს თვლიან.',
    },
    category: 'mathematics',
    difficulty: 3,
    relatedFormulaIds: ['cosine-rule'],
    topicIds: ['parallax'],
  },
  {
    id: 'cosine-rule',
    subjectId: 'trigonometry',
    name: { ka: 'კოსინუსების თეორემა' },
    expression: 'c² = a² + b² − 2ab·cos C',
    variables: [
      { symbol: 'a, b, c', meaning: { ka: 'სამკუთხედის გვერდები' }, unit: 'm' },
      { symbol: 'C', meaning: { ka: 'c გვერდის მოპირდაპირე კუთხე' }, unit: '°' },
    ],
    explanation: {
      ka: 'პითაგორას თეორემის განზოგადება ნებისმიერ სამკუთხედზე. თუ C = 90°, მაშინ cos 90° = 0 და ფორმულა ზუსტად პითაგორად იქცევა.',
    },
    category: 'mathematics',
    difficulty: 3,
    relatedFormulaIds: ['pythagoras', 'sine-rule'],
  },
  {
    id: 'golden-ratio',
    subjectId: 'math',
    name: { ka: 'ოქროს კვეთა' },
    expression: 'φ = (1 + √5) / 2 ≈ 1.6180339887',
    variables: [{ symbol: 'φ', meaning: { ka: 'ოქროს კვეთის რიცხვი' } }],
    explanation: {
      ka: 'ერთადერთი რიცხვი, რომლისთვისაც φ² = φ + 1. ფიბონაჩის მიმდევრობის მეზობელი წევრების შეფარდება სწორედ ამ რიცხვს უახლოვდება. ბუნებაში ხშირად გვხვდება არა სილამაზის, არამედ ეფექტურობის გამო — ასე ეწყობა ფოთლები ისე, რომ ერთმანეთს ჩრდილი ნაკლებად მიაყენონ.',
    },
    category: 'mathematics',
    difficulty: 2,
    topicIds: ['fibonacci'],
  },
  {
    id: 'euler-polyhedron',
    subjectId: 'geometry',
    name: { ka: 'ეილერის ფორმულა მრავალწახნაგისთვის' },
    expression: 'V − E + F = 2',
    variables: [
      { symbol: 'V', meaning: { ka: 'წვეროების რაოდენობა' } },
      { symbol: 'E', meaning: { ka: 'წიბოების რაოდენობა' } },
      { symbol: 'F', meaning: { ka: 'წახნაგების რაოდენობა' } },
    ],
    explanation: {
      ka: 'ნებისმიერი ამოზნექილი მრავალწახნაგისთვის ეს ჯამი ყოველთვის 2-ია — კუბისთვისაც და ფეხბურთის ბურთისთვისაც. ეს ტოპოლოგიის ერთ-ერთი პირველი შედეგია: ის ფორმაზე კი არა, „ხვრელების რაოდენობაზე" არის დამოკიდებული.',
    },
    example: { ka: 'კუბი: 8 − 12 + 6 = 2.' },
    category: 'mathematics',
    difficulty: 3,
  },
  {
    id: 'log-product',
    subjectId: 'algebra',
    name: { ka: 'ლოგარითმის თვისებები' },
    expression: 'log(ab) = log a + log b,   log(aⁿ) = n·log a',
    variables: [{ symbol: 'a, b', meaning: { ka: 'დადებითი რიცხვები' } }],
    explanation: {
      ka: 'ლოგარითმი გამრავლებას შეკრებად აქცევს. სწორედ ამიტომ იყო ლოგარითმული სახაზავი 300 წლის განმავლობაში ინჟინრის მთავარი იარაღი — და ამიტომვე იზომება ხმა და მიწისძვრა ლოგარითმულ სკალაზე.',
    },
    category: 'mathematics',
    difficulty: 2,
    topicIds: ['logarithms'],
  },

  /* ===================== ფიზიკა ===================== */
  {
    id: 'newton-second',
    subjectId: 'physics',
    name: { ka: 'ნიუტონის მეორე კანონი' },
    expression: 'F = m·a',
    variables: [
      { symbol: 'F', meaning: { ka: 'სხეულზე მოქმედი ჯამური ძალა' }, unit: 'N' },
      { symbol: 'm', meaning: { ka: 'მასა — წინააღმდეგობა აჩქარების მიმართ' }, unit: 'kg' },
      { symbol: 'a', meaning: { ka: 'აჩქარება — სიჩქარის ცვლილების ტემპი' }, unit: 'm/s²' },
    ],
    explanation: {
      ka: 'ყველაზე ხშირი შეცდომა: ვფიქრობთ, ძალა მოძრაობას იწვევს. სინამდვილეში ძალა მოძრაობის *ცვლილებას* იწვევს. თანაბრად და სწორხაზოვნად მოძრავ სხეულს ძალა საერთოდ არ სჭირდება — მას მხოლოდ მაშინ სჭირდება, როცა უნდა აჩქარდეს, შენელდეს ან მიმართულება შეიცვალოს.',
    },
    example: {
      ka: '1500 კგ ავტომობილს რომ 0-დან 100 კმ/სთ-მდე 8 წამში აჩქარდეს, სჭირდება a ≈ 3.5 მ/წმ² და ძალა F ≈ 5200 ნ.',
    },
    category: 'physics',
    difficulty: 2,
    relatedFormulaIds: ['momentum', 'kinetic-energy', 'gravitation'],
    topicIds: ['newton-laws'],
    sources: [S.hyperphysics],
  },
  {
    id: 'gravitation',
    subjectId: 'physics',
    name: { ka: 'მსოფლიო მიზიდულობის კანონი' },
    expression: 'F = G · m₁m₂ / r²',
    variables: [
      { symbol: 'F', meaning: { ka: 'მიზიდულობის ძალა' }, unit: 'N' },
      { symbol: 'G', meaning: { ka: 'გრავიტაციული მუდმივა = 6.674 × 10⁻¹¹' }, unit: 'N·m²/kg²' },
      { symbol: 'm₁, m₂', meaning: { ka: 'ორი სხეულის მასები' }, unit: 'kg' },
      { symbol: 'r', meaning: { ka: 'მანძილი ცენტრებს შორის' }, unit: 'm' },
    ],
    explanation: {
      ka: 'r კვადრატშია მნიშვნელში — ანუ მანძილის გაორმაგებისას ძალა ოთხჯერ სუსტდება. ნიუტონის ნამდვილი აღმოჩენა ის კი არ იყო, რომ ვაშლი ეცემა, არამედ რომ ვაშლის დაცემა და მთვარის ბრუნვა ერთი და იმავე კანონის ორი გამოვლინებაა.',
    },
    example: {
      ka: 'დედამიწა (5.97 × 10²⁴ კგ) და 70 კგ ადამიანი ზედაპირზე (r ≈ 6371 კმ) → F ≈ 686 ნ, ანუ დაახლოებით 70 კგ წონა.',
    },
    category: 'physics',
    difficulty: 3,
    relatedFormulaIds: ['newton-second', 'escape-velocity', 'schwarzschild'],
    topicIds: ['gravity', 'black-holes'],
    sources: [S.nist],
  },
  {
    id: 'mass-energy',
    subjectId: 'physics',
    name: { ka: 'მასისა და ენერგიის ეკვივალენტობა' },
    expression: 'E = mc²',
    variables: [
      { symbol: 'E', meaning: { ka: 'ენერგია' }, unit: 'J' },
      { symbol: 'm', meaning: { ka: 'მასა' }, unit: 'kg' },
      { symbol: 'c', meaning: { ka: 'სინათლის სიჩქარე ვაკუუმში = 299 792 458' }, unit: 'm/s' },
    ],
    explanation: {
      ka: 'მასა და ენერგია ერთი და იმავე რამის ორი ფორმაა. c² უზარმაზარი მამრავლია, ამიტომ ძალიან პატარა მასაც კი გიგანტურ ენერგიას შეესაბამება. სწორედ ამიტომ ანათებს მზე: ის წამში დაახლოებით 4 მილიონ ტონა მასას ენერგიად აქცევს.',
    },
    example: {
      ka: '1 გრამი მასა = 9 × 10¹³ ჯოული — დაახლოებით იმდენი, რამდენსაც პატარა ქალაქი დღეში მოიხმარს.',
    },
    category: 'physics',
    difficulty: 3,
    relatedFormulaIds: ['lorentz-time', 'photon-energy'],
    topicIds: ['relativity'],
    sources: [S.nist],
  },
  {
    id: 'kinetic-energy',
    subjectId: 'physics',
    name: { ka: 'კინეტიკური ენერგია' },
    expression: 'Eₖ = ½mv²',
    variables: [
      { symbol: 'Eₖ', meaning: { ka: 'მოძრაობის ენერგია' }, unit: 'J' },
      { symbol: 'm', meaning: { ka: 'მასა' }, unit: 'kg' },
      { symbol: 'v', meaning: { ka: 'სიჩქარე' }, unit: 'm/s' },
    ],
    explanation: {
      ka: 'სიჩქარე კვადრატშია — ეს ყოველდღიური უსაფრთხოების საკითხია. ორჯერ სწრაფად მოძრავ ავტომობილს ოთხჯერ მეტი ენერგია აქვს და, შესაბამისად, დაახლოებით ოთხჯერ გრძელი დამუხრუჭების მანძილი სჭირდება.',
    },
    example: { ka: '1000 კგ ავტომობილი 20 მ/წმ-ზე → Eₖ = 200 000 ჯ. 40 მ/წმ-ზე → 800 000 ჯ.' },
    category: 'physics',
    difficulty: 2,
    relatedFormulaIds: ['potential-energy', 'momentum', 'work'],
    topicIds: ['energy'],
  },
  {
    id: 'potential-energy',
    subjectId: 'physics',
    name: { ka: 'პოტენციური ენერგია სიმძიმის ველში' },
    expression: 'Eₚ = mgh',
    variables: [
      { symbol: 'Eₚ', meaning: { ka: 'პოტენციური ენერგია' }, unit: 'J' },
      { symbol: 'g', meaning: { ka: 'თავისუფალი ვარდნის აჩქარება ≈ 9.81' }, unit: 'm/s²' },
      { symbol: 'h', meaning: { ka: 'სიმაღლე ათვლის დონიდან' }, unit: 'm' },
    ],
    explanation: {
      ka: 'ეს „დაგროვილი" ენერგიაა, რომელიც სიმაღლიდან ვარდნისას კინეტიკურად გარდაიქმნება. ჰიდროელექტროსადგური ზუსტად ამას აკეთებს: წყალს სიმაღლეს აძლევს, შემდეგ კი ვარდნის ენერგიას იჭერს.',
    },
    category: 'physics',
    difficulty: 2,
    relatedFormulaIds: ['kinetic-energy'],
    topicIds: ['energy'],
  },
  {
    id: 'momentum',
    subjectId: 'physics',
    name: { ka: 'იმპულსი' },
    expression: 'p = m·v',
    variables: [
      { symbol: 'p', meaning: { ka: 'იმპულსი — ვექტორული სიდიდე' }, unit: 'kg·m/s' },
      { symbol: 'm', meaning: { ka: 'მასა' }, unit: 'kg' },
      { symbol: 'v', meaning: { ka: 'სიჩქარე' }, unit: 'm/s' },
    ],
    explanation: {
      ka: 'ჩაკეტილ სისტემაში ჯამური იმპულსი არასოდეს იცვლება. ეს ერთ-ერთი ყველაზე ღრმა კანონია ფიზიკაში — და სწორედ ის ხსნის, როგორ მოძრაობს რაკეტა კოსმოსში, სადაც არაფერზეა დასაყრდნობი: ის აირს უკან ისვრის, თვითონ კი წინ მიდის.',
    },
    category: 'physics',
    difficulty: 2,
    relatedFormulaIds: ['newton-second', 'kinetic-energy'],
    topicIds: ['newton-laws'],
  },
  {
    id: 'work',
    subjectId: 'physics',
    name: { ka: 'მუშაობა' },
    expression: 'W = F·d·cos θ',
    variables: [
      { symbol: 'W', meaning: { ka: 'შესრულებული მუშაობა' }, unit: 'J' },
      { symbol: 'F', meaning: { ka: 'ძალა' }, unit: 'N' },
      { symbol: 'd', meaning: { ka: 'გადაადგილება' }, unit: 'm' },
      { symbol: 'θ', meaning: { ka: 'კუთხე ძალასა და გადაადგილებას შორის' }, unit: '°' },
    ],
    explanation: {
      ka: 'თუ ჩანთას ხელში გიჭირავს და სწორ გზაზე მიდიხარ, ფიზიკის თვალსაზრისით მუშაობას საერთოდ არ ასრულებ: ძალა ზემოთაა მიმართული, მოძრაობა კი წინ — cos 90° = 0.',
    },
    category: 'physics',
    difficulty: 2,
    relatedFormulaIds: ['kinetic-energy', 'power'],
    topicIds: ['energy'],
  },
  {
    id: 'power',
    subjectId: 'physics',
    name: { ka: 'სიმძლავრე' },
    expression: 'P = W / t',
    variables: [
      { symbol: 'P', meaning: { ka: 'სიმძლავრე' }, unit: 'W' },
      { symbol: 'W', meaning: { ka: 'მუშაობა ან ენერგია' }, unit: 'J' },
      { symbol: 't', meaning: { ka: 'დრო' }, unit: 's' },
    ],
    explanation: {
      ka: 'სიმძლავრე არ არის ენერგია — ეს ენერგიის ხარჯვის *ტემპია*. ორ ადამიანს, რომლებმაც ერთი და იგივე კიბე აიარეს, ერთნაირი მუშაობა აქვთ შესრულებული, მაგრამ ვინც სწრაფად ავიდა, მეტი სიმძლავრე განავითარა.',
    },
    category: 'physics',
    difficulty: 2,
    relatedFormulaIds: ['work', 'ohm'],
  },
  {
    id: 'ohm',
    subjectId: 'physics',
    name: { ka: 'ომის კანონი' },
    expression: 'V = I·R',
    variables: [
      { symbol: 'V', meaning: { ka: 'ძაბვა — რა „აწვება" მუხტებს' }, unit: 'V' },
      { symbol: 'I', meaning: { ka: 'დენის ძალა — რამდენი მუხტი გადის წამში' }, unit: 'A' },
      { symbol: 'R', meaning: { ka: 'წინაღობა — რამდენად უშლის ხელს გამტარი' }, unit: 'Ω' },
    ],
    explanation: {
      ka: 'კარგი ანალოგია მილში მიმდინარე წყალია: ძაბვა წნევაა, დენი — ნაკადი, წინაღობა კი მილის სივიწროვე. ერთი ცნობილი გამონაკლისი: ეს კანონი ყველა მასალაზე არ ვრცელდება — მაგალითად, დიოდზე არა.',
    },
    example: { ka: '12 ვ ბატარეა და 4 Ω წინაღობა → I = 12 / 4 = 3 ა.' },
    category: 'physics',
    difficulty: 2,
    relatedFormulaIds: ['power', 'coulomb'],
    topicIds: ['electricity'],
  },
  {
    id: 'coulomb',
    subjectId: 'physics',
    name: { ka: 'კულონის კანონი' },
    expression: 'F = k · q₁q₂ / r²',
    variables: [
      { symbol: 'F', meaning: { ka: 'ელექტრული ძალა' }, unit: 'N' },
      { symbol: 'k', meaning: { ka: 'კულონის მუდმივა ≈ 8.99 × 10⁹' }, unit: 'N·m²/C²' },
      { symbol: 'q₁, q₂', meaning: { ka: 'მუხტები' }, unit: 'C' },
      { symbol: 'r', meaning: { ka: 'მანძილი' }, unit: 'm' },
    ],
    explanation: {
      ka: 'ფორმა ზუსტად ისეთივეა, როგორიც მიზიდულობის კანონს აქვს — მაგრამ ელექტრული ძალა უზომოდ უფრო ძლიერია. ორი ელექტრონი ერთმანეთს ელექტრულად დაახლოებით 10⁴² -ჯერ უფრო ძლიერად განიზიდავს, ვიდრე გრავიტაციულად იზიდავს.',
    },
    category: 'physics',
    difficulty: 3,
    relatedFormulaIds: ['gravitation', 'ohm'],
    topicIds: ['electricity'],
  },
  {
    id: 'wave-speed',
    subjectId: 'physics',
    name: { ka: 'ტალღის სიჩქარე' },
    expression: 'v = f·λ',
    variables: [
      { symbol: 'v', meaning: { ka: 'ტალღის გავრცელების სიჩქარე' }, unit: 'm/s' },
      { symbol: 'f', meaning: { ka: 'სიხშირე — რამდენი რხევაა წამში' }, unit: 'Hz' },
      { symbol: 'λ', meaning: { ka: 'ტალღის სიგრძე' }, unit: 'm' },
    ],
    explanation: {
      ka: 'მოცემულ გარემოში სიჩქარე მუდმივია, ამიტომ სიხშირე და ტალღის სიგრძე ერთმანეთის უკუპროპორციულია: მაღალი ტონი = მოკლე ტალღა.',
    },
    example: { ka: 'რადიოსადგური 100 MHz-ზე: λ = 3 × 10⁸ / 10⁸ = 3 მეტრი.' },
    category: 'physics',
    difficulty: 2,
    relatedFormulaIds: ['photon-energy', 'snell'],
    topicIds: ['waves', 'light'],
  },
  {
    id: 'photon-energy',
    subjectId: 'physics',
    name: { ka: 'ფოტონის ენერგია' },
    expression: 'E = h·f = hc / λ',
    variables: [
      { symbol: 'E', meaning: { ka: 'ერთი ფოტონის ენერგია' }, unit: 'J' },
      { symbol: 'h', meaning: { ka: 'პლანკის მუდმივა = 6.626 × 10⁻³⁴' }, unit: 'J·s' },
      { symbol: 'f', meaning: { ka: 'სიხშირე' }, unit: 'Hz' },
    ],
    explanation: {
      ka: 'სინათლე უწყვეტი ნაკადი კი არა, ულუფებად — ფოტონებად — მოდის. ამიტომ სუსტი ულტრაიისფერი შეიძლება უფრო საშიში იყოს, ვიდრე ძლიერი წითელი შუქი: მნიშვნელოვანია ცალკეული ფოტონის ენერგია, არა მათი რაოდენობა.',
    },
    category: 'physics',
    difficulty: 3,
    relatedFormulaIds: ['wave-speed', 'de-broglie', 'mass-energy'],
    topicIds: ['quantum', 'light'],
    sources: [S.nist],
  },
  {
    id: 'de-broglie',
    subjectId: 'physics',
    name: { ka: 'დე ბროილის ტალღის სიგრძე' },
    expression: 'λ = h / p',
    variables: [
      { symbol: 'λ', meaning: { ka: 'ნაწილაკის ტალღის სიგრძე' }, unit: 'm' },
      { symbol: 'p', meaning: { ka: 'იმპულსი' }, unit: 'kg·m/s' },
    ],
    explanation: {
      ka: 'ყველა ნაწილაკს ტალღური თვისებები აქვს — ელექტრონსაც და შენც. უბრალოდ, ადამიანის იმპულსი იმდენად დიდია, რომ ტალღის სიგრძე ატომზე მილიარდჯერ პატარაა და ვერასდროს შევამჩნევთ.',
    },
    category: 'physics',
    difficulty: 4,
    relatedFormulaIds: ['photon-energy', 'heisenberg'],
    topicIds: ['quantum'],
  },
  {
    id: 'heisenberg',
    subjectId: 'physics',
    name: { ka: 'ჰაიზენბერგის განუზღვრელობის პრინციპი' },
    expression: 'Δx · Δp ≥ ħ / 2',
    variables: [
      { symbol: 'Δx', meaning: { ka: 'კოორდინატის განუზღვრელობა' }, unit: 'm' },
      { symbol: 'Δp', meaning: { ka: 'იმპულსის განუზღვრელობა' }, unit: 'kg·m/s' },
      { symbol: 'ħ', meaning: { ka: 'დაყვანილი პლანკის მუდმივა = h/2π' }, unit: 'J·s' },
    ],
    explanation: {
      ka: 'ეს ხელსაწყოების სიზუსტის პრობლემა არ არის — ეს ბუნების თვისებაა. ნაწილაკს ერთდროულად ზუსტი კოორდინატიც და ზუსტი იმპულსიც უბრალოდ *არ გააჩნია*. რაც ერთს უფრო ზუსტად განსაზღვრავ, მით უფრო ბუნდოვანი ხდება მეორე.',
    },
    category: 'physics',
    difficulty: 4,
    relatedFormulaIds: ['de-broglie'],
    topicIds: ['quantum'],
  },
  {
    id: 'escape-velocity',
    subjectId: 'astronomy',
    name: { ka: 'მეორე კოსმოსური სიჩქარე' },
    expression: 'v = √(2GM / r)',
    variables: [
      { symbol: 'v', meaning: { ka: 'სიჩქარე, რომელიც მიზიდულობისგან თავის დასაღწევადაა საჭირო' }, unit: 'm/s' },
      { symbol: 'M', meaning: { ka: 'ციური სხეულის მასა' }, unit: 'kg' },
      { symbol: 'r', meaning: { ka: 'მანძილი ცენტრიდან' }, unit: 'm' },
    ],
    explanation: {
      ka: 'დედამიწისთვის ეს დაახლოებით 11.2 კმ/წმ-ია. საინტერესო ის არის, რომ სიდიდე მოძრავი სხეულის მასაზე *არ არის* დამოკიდებული — ბურთისთვისაც და რაკეტისთვისაც ერთი და იგივეა.',
    },
    example: { ka: 'მთვარე: 2.4 კმ/წმ. მზე ზედაპირიდან: 618 კმ/წმ.' },
    category: 'physics',
    difficulty: 3,
    relatedFormulaIds: ['gravitation', 'schwarzschild'],
    topicIds: ['black-holes', 'gravity'],
  },
  {
    id: 'schwarzschild',
    subjectId: 'astronomy',
    name: { ka: 'შვარცშილდის რადიუსი' },
    expression: 'rₛ = 2GM / c²',
    variables: [
      { symbol: 'rₛ', meaning: { ka: 'მოვლენათა ჰორიზონტის რადიუსი' }, unit: 'm' },
      { symbol: 'M', meaning: { ka: 'შავი ხვრელის მასა' }, unit: 'kg' },
      { symbol: 'c', meaning: { ka: 'სინათლის სიჩქარე' }, unit: 'm/s' },
    ],
    explanation: {
      ka: 'ეს ის ზღვარია, საიდანაც სინათლესაც კი აღარ შეუძლია გამოსვლა — მეორე კოსმოსური სიჩქარე სწორედ აქ უტოლდება c-ს. ყურადღება: ეს „ზედაპირი" არ არის, არამედ საზღვარი სივრცეში.',
    },
    example: {
      ka: 'თუ მზეს შავ ხვრელად ვაქცევდით, მისი რადიუსი მხოლოდ 3 კმ იქნებოდა. დედამიწისთვის — 9 მილიმეტრი.',
    },
    category: 'physics',
    difficulty: 4,
    relatedFormulaIds: ['gravitation', 'escape-velocity', 'mass-energy'],
    topicIds: ['black-holes'],
  },
  {
    id: 'lorentz-time',
    subjectId: 'physics',
    name: { ka: 'დროის შენელება' },
    expression: 'Δt = Δt₀ / √(1 − v²/c²)',
    variables: [
      { symbol: 'Δt', meaning: { ka: 'დრო უძრავი დამკვირვებლისთვის' }, unit: 's' },
      { symbol: 'Δt₀', meaning: { ka: 'საკუთარი დრო — მოძრავ სისტემაში' }, unit: 's' },
      { symbol: 'v', meaning: { ka: 'ფარდობითი სიჩქარე' }, unit: 'm/s' },
    ],
    explanation: {
      ka: 'რაც უფრო სწრაფად მოძრაობ, მით ნელა მიდის შენი დრო სხვისი გადმოსახედიდან. ეს ფანტასტიკა არ არის: GPS თანამგზავრები ყოველდღე ითვალისწინებენ ამ ეფექტს — მის გარეშე ნავიგაცია დღეში დაახლოებით 10 კილომეტრით აცდებოდა.',
    },
    category: 'physics',
    difficulty: 4,
    relatedFormulaIds: ['mass-energy'],
    topicIds: ['relativity'],
  },
  {
    id: 'ideal-gas',
    subjectId: 'physics',
    name: { ka: 'იდეალური აირის განტოლება' },
    expression: 'pV = nRT',
    variables: [
      { symbol: 'p', meaning: { ka: 'წნევა' }, unit: 'Pa' },
      { symbol: 'V', meaning: { ka: 'მოცულობა' }, unit: 'm³' },
      { symbol: 'n', meaning: { ka: 'ნივთიერების რაოდენობა' }, unit: 'mol' },
      { symbol: 'R', meaning: { ka: 'უნივერსალური აირის მუდმივა = 8.314' }, unit: 'J/(mol·K)' },
      { symbol: 'T', meaning: { ka: 'აბსოლუტური ტემპერატურა' }, unit: 'K' },
    ],
    explanation: {
      ka: 'ერთ განტოლებაში სამი კანონია გაერთიანებული. მთავარი პირობა: T კელვინებში უნდა იყოს, არა ცელსიუსში — რადგან ფორმულა აბსოლუტურ ნულს ეყრდნობა.',
    },
    category: 'physics',
    difficulty: 3,
    relatedFormulaIds: ['moles'],
    topicIds: ['thermodynamics'],
  },
  {
    id: 'pendulum',
    subjectId: 'physics',
    name: { ka: 'მათემატიკური ქანქარის პერიოდი' },
    expression: 'T = 2π · √(L / g)',
    variables: [
      { symbol: 'T', meaning: { ka: 'ერთი სრული რხევის დრო' }, unit: 's' },
      { symbol: 'L', meaning: { ka: 'ძაფის სიგრძე' }, unit: 'm' },
      { symbol: 'g', meaning: { ka: 'თავისუფალი ვარდნის აჩქარება' }, unit: 'm/s²' },
    ],
    explanation: {
      ka: 'ყველაზე გასაკვირი ის არის, რომ პერიოდი ტვირთის მასაზე *არ არის* დამოკიდებული — მხოლოდ სიგრძეზე. სწორედ ამან აქცია ქანქარა 300 წლის განმავლობაში ყველაზე ზუსტ საათად.',
    },
    example: { ka: '1 მეტრიანი ქანქარა დედამიწაზე: T ≈ 2.0 წამი.' },
    category: 'physics',
    difficulty: 3,
    relatedFormulaIds: ['hookes'],
  },
  {
    id: 'hookes',
    subjectId: 'physics',
    name: { ka: 'ჰუკის კანონი' },
    expression: 'F = −k·x',
    variables: [
      { symbol: 'F', meaning: { ka: 'დრეკადობის ძალა' }, unit: 'N' },
      { symbol: 'k', meaning: { ka: 'ზამბარის სიხისტე' }, unit: 'N/m' },
      { symbol: 'x', meaning: { ka: 'დეფორმაცია' }, unit: 'm' },
    ],
    explanation: {
      ka: 'მინუსი შემთხვევითი არ არის: ძალა ყოველთვის დეფორმაციის *საწინააღმდეგოდაა* მიმართული — ზამბარა ცდილობს საწყის მდგომარეობას დაუბრუნდეს.',
    },
    category: 'physics',
    difficulty: 2,
    relatedFormulaIds: ['pendulum', 'stress'],
  },
  {
    id: 'snell',
    subjectId: 'physics',
    name: { ka: 'სნელის კანონი' },
    expression: 'n₁ · sin θ₁ = n₂ · sin θ₂',
    variables: [
      { symbol: 'n₁, n₂', meaning: { ka: 'გარემოების გარდატეხის მაჩვენებლები' } },
      { symbol: 'θ₁, θ₂', meaning: { ka: 'დაცემისა და გარდატეხის კუთხეები' }, unit: '°' },
    ],
    explanation: {
      ka: 'სინათლე გარემოს საზღვარზე მიმართულებას იცვლის, რადგან სხვადასხვა გარემოში სხვადასხვა სიჩქარით ვრცელდება. ამიტომ ჩანს წყალში ჩაშვებული ჯოხი „გატეხილი" — და ამიტომ მუშაობს ლინზა.',
    },
    category: 'physics',
    difficulty: 3,
    relatedFormulaIds: ['wave-speed'],
    topicIds: ['light'],
  },
  {
    id: 'centripetal',
    subjectId: 'physics',
    name: { ka: 'ცენტრისკენული აჩქარება' },
    expression: 'a = v² / r',
    variables: [
      { symbol: 'a', meaning: { ka: 'ცენტრისკენ მიმართული აჩქარება' }, unit: 'm/s²' },
      { symbol: 'v', meaning: { ka: 'წრფივი სიჩქარე' }, unit: 'm/s' },
      { symbol: 'r', meaning: { ka: 'წრეწირის რადიუსი' }, unit: 'm' },
    ],
    explanation: {
      ka: 'წრეზე თანაბრად მოძრავი სხეულის სიჩქარის მოდული არ იცვლება, მაგრამ მიმართულება მუდმივად იცვლება — ეს კი უკვე აჩქარებაა. სწორედ ამიტომ სჭირდება მთვარეს დედამიწის მიზიდულობა, რომ ორბიტაზე დარჩეს.',
    },
    category: 'physics',
    difficulty: 3,
    relatedFormulaIds: ['newton-second', 'gravitation'],
    topicIds: ['gravity'],
  },
  {
    id: 'density',
    subjectId: 'physics',
    name: { ka: 'სიმკვრივე' },
    expression: 'ρ = m / V',
    variables: [
      { symbol: 'ρ', meaning: { ka: 'სიმკვრივე' }, unit: 'kg/m³' },
      { symbol: 'm', meaning: { ka: 'მასა' }, unit: 'kg' },
      { symbol: 'V', meaning: { ka: 'მოცულობა' }, unit: 'm³' },
    ],
    explanation: {
      ka: 'რატომ ცურავს ხე და იძირება ქვა — მთელი პასუხი აქაა. სხეული ცურავს, თუ მისი საშუალო სიმკვრივე სითხის სიმკვრივეზე ნაკლებია. ფოლადის გემი სწორედ ამიტომ არ იძირება: შიგნით ჰაერია.',
    },
    category: 'physics',
    difficulty: 1,
    relatedFormulaIds: ['ideal-gas'],
  },
  {
    id: 'stefan-boltzmann',
    subjectId: 'astronomy',
    name: { ka: 'სტეფან-ბოლცმანის კანონი' },
    expression: 'P = σ·A·T⁴',
    variables: [
      { symbol: 'P', meaning: { ka: 'გამოსხივების სიმძლავრე' }, unit: 'W' },
      { symbol: 'σ', meaning: { ka: 'სტეფან-ბოლცმანის მუდმივა = 5.67 × 10⁻⁸' }, unit: 'W/(m²·K⁴)' },
      { symbol: 'A', meaning: { ka: 'ზედაპირის ფართობი' }, unit: 'm²' },
      { symbol: 'T', meaning: { ka: 'ტემპერატურა კელვინებში' }, unit: 'K' },
    ],
    explanation: {
      ka: 'ტემპერატურა მეოთხე ხარისხშია — ეს ძალიან ციცაბო დამოკიდებულებაა. ორჯერ ცხელი ვარსკვლავი 16-ჯერ მეტ ენერგიას ასხივებს. სწორედ ამიტომ ანათებენ ცისფერი ვარსკვლავები ასე კაშკაშა და ცხოვრობენ ასე ცოტა ხანს.',
    },
    category: 'physics',
    difficulty: 4,
    relatedFormulaIds: ['photon-energy'],
    topicIds: ['stars'],
  },
  {
    id: 'hubble',
    subjectId: 'astronomy',
    name: { ka: 'ჰაბლ-ლემეტრის კანონი' },
    expression: 'v = H₀ · d',
    variables: [
      { symbol: 'v', meaning: { ka: 'გალაქტიკის დაშორების სიჩქარე' }, unit: 'km/s' },
      { symbol: 'H₀', meaning: { ka: 'ჰაბლის მუდმივა ≈ 70' }, unit: 'km/s/Mpc' },
      { symbol: 'd', meaning: { ka: 'მანძილი გალაქტიკამდე' }, unit: 'Mpc' },
    ],
    explanation: {
      ka: 'რაც უფრო შორსაა გალაქტიკა, მით უფრო სწრაფად შორდება — სამყარო ფართოვდება. მნიშვნელოვანი დაზუსტება: გალაქტიკები სივრცეში კი არ „გარბიან", თვითონ სივრცე იზრდება მათ შორის.',
    },
    category: 'physics',
    difficulty: 4,
    topicIds: ['cosmology'],
  },

  /* ===================== ქიმია ===================== */
  {
    id: 'moles',
    subjectId: 'chemistry',
    name: { ka: 'ნივთიერების რაოდენობა' },
    expression: 'n = m / M',
    variables: [
      { symbol: 'n', meaning: { ka: 'ნივთიერების რაოდენობა' }, unit: 'mol' },
      { symbol: 'm', meaning: { ka: 'მასა' }, unit: 'g' },
      { symbol: 'M', meaning: { ka: 'მოლური მასა' }, unit: 'g/mol' },
    ],
    explanation: {
      ka: 'მოლი ქიმიკოსის „ათეული"-ა: ის მასას ნაწილაკების რაოდენობად თარგმნის. რეაქციები ხომ გრამებში კი არა, ნაწილაკების თანაფარდობით მიმდინარეობს.',
    },
    example: { ka: '18 გ წყალი → n = 18 / 18 = 1 მოლი ≈ 6.022 × 10²³ მოლეკულა.' },
    category: 'chemistry',
    difficulty: 2,
    relatedFormulaIds: ['avogadro', 'molarity', 'ideal-gas'],
    topicIds: ['mole-concept'],
    sources: [S.iupac],
  },
  {
    id: 'avogadro',
    subjectId: 'chemistry',
    name: { ka: 'ავოგადროს რიცხვი' },
    expression: 'N = n · N_A,   N_A = 6.02214076 × 10²³ mol⁻¹',
    variables: [
      { symbol: 'N', meaning: { ka: 'ნაწილაკების რაოდენობა' } },
      { symbol: 'N_A', meaning: { ka: 'ავოგადროს მუდმივა' }, unit: 'mol⁻¹' },
    ],
    explanation: {
      ka: '2019 წლიდან ეს რიცხვი ზუსტად განსაზღვრულია — ის აღარ იზომება, არამედ თვითონ განსაზღვრავს მოლს. რამდენად დიდია? ერთი მოლი ბრინჯის მარცვალი მთელ დედამიწას რამდენიმე კილომეტრიანი ფენით დაფარავდა.',
    },
    category: 'chemistry',
    difficulty: 2,
    relatedFormulaIds: ['moles'],
    topicIds: ['mole-concept'],
    sources: [S.nist],
  },
  {
    id: 'molarity',
    subjectId: 'chemistry',
    name: { ka: 'მოლური კონცენტრაცია' },
    expression: 'c = n / V',
    variables: [
      { symbol: 'c', meaning: { ka: 'კონცენტრაცია' }, unit: 'mol/L' },
      { symbol: 'n', meaning: { ka: 'გახსნილი ნივთიერების რაოდენობა' }, unit: 'mol' },
      { symbol: 'V', meaning: { ka: 'ხსნარის მოცულობა' }, unit: 'L' },
    ],
    explanation: {
      ka: 'ყურადღება: მნიშვნელში *ხსნარის* მოცულობაა, არა გამხსნელის. ეს ხშირი შეცდომაა ლაბორატორიულ გამოთვლებში.',
    },
    category: 'chemistry',
    difficulty: 2,
    relatedFormulaIds: ['moles', 'dilution', 'ph'],
  },
  {
    id: 'dilution',
    subjectId: 'chemistry',
    name: { ka: 'განზავების ფორმულა' },
    expression: 'c₁V₁ = c₂V₂',
    variables: [
      { symbol: 'c₁, V₁', meaning: { ka: 'საწყისი კონცენტრაცია და მოცულობა' } },
      { symbol: 'c₂, V₂', meaning: { ka: 'საბოლოო კონცენტრაცია და მოცულობა' } },
    ],
    explanation: {
      ka: 'განზავებისას ნივთიერების რაოდენობა არ იცვლება — მხოლოდ მოცულობა იზრდება. ამიტომაა ორივე მხარეს ერთი და იგივე n.',
    },
    category: 'chemistry',
    difficulty: 2,
    relatedFormulaIds: ['molarity'],
  },
  {
    id: 'ph',
    subjectId: 'chemistry',
    name: { ka: 'წყალბადის მაჩვენებელი' },
    expression: 'pH = −log₁₀[H⁺]',
    variables: [
      { symbol: 'pH', meaning: { ka: 'მჟავიანობის მაჩვენებელი, 0–14' } },
      { symbol: '[H⁺]', meaning: { ka: 'წყალბადის იონების კონცენტრაცია' }, unit: 'mol/L' },
    ],
    explanation: {
      ka: 'სკალა ლოგარითმულია: pH 4 არა ორჯერ, არამედ ასჯერ უფრო მჟავეა, ვიდრე pH 6. სუფთა წყალს 25 °C-ზე pH = 7 აქვს.',
    },
    example: { ka: 'ლიმონის წვენი ≈ pH 2, სისხლი ≈ 7.4, ზღვის წყალი ≈ 8.1.' },
    category: 'chemistry',
    difficulty: 3,
    relatedFormulaIds: ['molarity', 'log-product'],
    sources: [S.iupac],
  },

  /* ===================== სტატისტიკა ===================== */
  {
    id: 'mean',
    subjectId: 'statistics',
    name: { ka: 'საშუალო არითმეტიკული' },
    expression: 'x̄ = (x₁ + x₂ + … + xₙ) / n',
    variables: [
      { symbol: 'x̄', meaning: { ka: 'საშუალო მნიშვნელობა' } },
      { symbol: 'n', meaning: { ka: 'დაკვირვებების რაოდენობა' } },
    ],
    explanation: {
      ka: 'საშუალო ერთ რიცხვში კრებს მთელ მონაცემებს — და სწორედ ეს არის მისი სისუსტე. ერთი უზარმაზარი მნიშვნელობა მას მთლიანად ამახინჯებს; ასეთ შემთხვევაში მედიანა ბევრად პატიოსანი მაჩვენებელია.',
    },
    category: 'statistics',
    difficulty: 1,
    relatedFormulaIds: ['std-dev', 'z-score'],
    topicIds: ['statistics-basics'],
  },
  {
    id: 'std-dev',
    subjectId: 'statistics',
    name: { ka: 'სტანდარტული გადახრა' },
    expression: 'σ = √( Σ(xᵢ − μ)² / N )',
    variables: [
      { symbol: 'σ', meaning: { ka: 'სტანდარტული გადახრა' } },
      { symbol: 'μ', meaning: { ka: 'საშუალო მნიშვნელობა' } },
      { symbol: 'N', meaning: { ka: 'მონაცემთა რაოდენობა' } },
    ],
    explanation: {
      ka: 'პასუხობს კითხვას: „რამდენად მიმოფანტულია მონაცემები საშუალოს გარშემო?" ორ ჯგუფს შეიძლება ერთი და იგივე საშუალო ჰქონდეს, მაგრამ სრულიად განსხვავებული სურათი — და ამას სწორედ σ აჩვენებს.',
    },
    category: 'statistics',
    difficulty: 3,
    relatedFormulaIds: ['mean', 'z-score'],
    topicIds: ['statistics-basics'],
  },
  {
    id: 'z-score',
    subjectId: 'statistics',
    name: { ka: 'სტანდარტიზებული მნიშვნელობა' },
    expression: 'z = (x − μ) / σ',
    variables: [
      { symbol: 'z', meaning: { ka: 'რამდენი სტანდარტული გადახრითაა x საშუალოდან დაშორებული' } },
    ],
    explanation: {
      ka: 'z საშუალებას გვაძლევს, სრულიად განსხვავებული სიდიდეები შევადაროთ — მაგალითად, მათემატიკის ქულა და სიმაღლე. ნორმალურ განაწილებაში მონაცემების დაახლოებით 68% |z| < 1 ფარგლებშია.',
    },
    category: 'statistics',
    difficulty: 3,
    relatedFormulaIds: ['mean', 'std-dev'],
    topicIds: ['statistics-basics'],
  },
  {
    id: 'bayes',
    subjectId: 'probability',
    name: { ka: 'ბაიესის თეორემა' },
    expression: 'P(A|B) = P(B|A) · P(A) / P(B)',
    variables: [
      { symbol: 'P(A|B)', meaning: { ka: 'A-ს ალბათობა იმ პირობით, რომ B მოხდა' } },
      { symbol: 'P(A)', meaning: { ka: 'A-ს საწყისი ალბათობა' } },
    ],
    explanation: {
      ka: 'ეს არის წესი, თუ როგორ უნდა შევცვალოთ აზრი ახალი მტკიცებულების მიღებისას. ყველაზე ცნობილი გაკვეთილი: თუ დაავადება იშვიათია, დადებითი ტესტიც კი შეიძლება უფრო ხშირად იყოს მცდარი, ვიდრე სწორი — რადგან P(A) ძალიან პატარაა.',
    },
    example: {
      ka: 'დაავადება 1000-დან 1-ს აქვს, ტესტი 99% ზუსტია. დადებითი პასუხის შემთხვევაში ავადმყოფობის ალბათობა მხოლოდ ≈ 9%-ია, არა 99%.',
    },
    category: 'statistics',
    difficulty: 4,
    relatedFormulaIds: ['combination'],
    topicIds: ['probability-basics'],
  },

  /* ===================== ინჟინერია და გამოთვლა ===================== */
  {
    id: 'shannon-entropy',
    subjectId: 'cs',
    name: { ka: 'შენონის ენტროპია' },
    expression: 'H = − Σ pᵢ · log₂(pᵢ)',
    variables: [
      { symbol: 'H', meaning: { ka: 'ინფორმაციის საშუალო რაოდენობა' }, unit: 'bit' },
      { symbol: 'pᵢ', meaning: { ka: 'i-ური შედეგის ალბათობა' } },
    ],
    explanation: {
      ka: 'ენტროპია ზომავს, რამდენად „მოულოდნელია" შეტყობინება. თუ პასუხი წინასწარ ცნობილია, ინფორმაცია ნულია. სწორედ ეს ფორმულა ადგენს ზღვარს, რომლის იქითაც ფაილის შეკუმშვა შეუძლებელია.',
    },
    example: {
      ka: 'სამართლიანი მონეტა: H = 1 ბიტი. მონეტა, რომელიც ყოველთვის ერთ მხარეს ვარდება: H = 0 ბიტი.',
    },
    category: 'computing',
    difficulty: 4,
    topicIds: ['information-theory'],
  },
  {
    id: 'binary-search-steps',
    subjectId: 'algorithms',
    name: { ka: 'ორობითი ძებნის ნაბიჯები' },
    expression: 'steps ≈ log₂(n)',
    variables: [
      { symbol: 'n', meaning: { ka: 'ელემენტების რაოდენობა დალაგებულ სიაში' } },
      { symbol: 'steps', meaning: { ka: 'შედარებების მაქსიმალური რაოდენობა' } },
    ],
    explanation: {
      ka: 'ყოველი ნაბიჯი სიას ნახევრად ჭრის. ეს იმდენად ძლიერია, რომ მილიონ ელემენტში ძებნა მხოლოდ 20 შედარებას მოითხოვს, მილიარდში — 30-ს.',
    },
    example: { ka: 'n = 1 000 000 → log₂(10⁶) ≈ 20 ნაბიჯი.' },
    category: 'computing',
    difficulty: 2,
    topicIds: ['algorithm-complexity'],
  },
  {
    id: 'stress',
    subjectId: 'engineering',
    name: { ka: 'მექანიკური ძაბვა' },
    expression: 'σ = F / A',
    variables: [
      { symbol: 'σ', meaning: { ka: 'ძაბვა' }, unit: 'Pa' },
      { symbol: 'F', meaning: { ka: 'მოქმედი ძალა' }, unit: 'N' },
      { symbol: 'A', meaning: { ka: 'განივკვეთის ფართობი' }, unit: 'm²' },
    ],
    explanation: {
      ka: 'მასალას არა ძალა, არამედ ძაბვა ანგრევს. ამიტომ თხელი მავთული იმავე ტვირთს ვერ უძლებს, რომელსაც სქელი ღერძი ადვილად იტანს — ფართობი მნიშვნელშია.',
    },
    category: 'engineering',
    difficulty: 3,
    relatedFormulaIds: ['hookes'],
  },
  {
    id: 'efficiency',
    subjectId: 'engineering',
    name: { ka: 'მარგი ქმედების კოეფიციენტი' },
    expression: 'η = (W_სასარგებლო / E_დახარჯული) × 100%',
    variables: [
      { symbol: 'η', meaning: { ka: 'მქკ' }, unit: '%' },
      { symbol: 'W_სასარგებლო', meaning: { ka: 'სასარგებლო მუშაობა' }, unit: 'J' },
    ],
    explanation: {
      ka: 'η ვერასოდეს იქნება 100% — თერმოდინამიკის მეორე კანონი კრძალავს. ბენზინის ძრავის მქკ ≈ 25–35%, ელექტროძრავის კი 90%-ს აღემატება.',
    },
    category: 'engineering',
    difficulty: 2,
    relatedFormulaIds: ['power', 'work'],
    topicIds: ['thermodynamics'],
  },
  {
    id: 'hash-load-factor',
    subjectId: 'programming',
    name: { ka: 'ჰეშ-ცხრილის დატვირთვის ფაქტორი' },
    expression: 'α = n / m',
    variables: [
      { symbol: 'α', meaning: { ka: 'დატვირთვის ფაქტორი — საშუალო ელემენტი ერთ „უჯრედზე"' } },
      { symbol: 'n', meaning: { ka: 'ცხრილში შენახული ელემენტების რაოდენობა' } },
      { symbol: 'm', meaning: { ka: 'უჯრედების (bucket) რაოდენობა' } },
    ],
    explanation: {
      ka: 'დატვირთვის ფაქტორი განსაზღვრავს, საშუალოდ რამდენ ელემენტს უწევს ერთ უჯრედის გაზიარება, ანუ რამდენად ხშირია შეჯახება. სანამ α მცირეა (ჩვეულებრივ < 0.75), ძებნა და ჩამატება საშუალოდ O(1)-შია. როცა α ამ ზღვარს გადააჭარბებს, ცხრილი ჩვეულებრივ ორმაგდება და ყველა ელემენტი ხელახლა ნაწილდება.',
    },
    example: { ka: 'n = 6 ელემენტი, m = 8 უჯრედი → α = 0.75. კიდევ ერთი ჩამატება გამოიწვევს ცხრილის გაფართოებას.' },
    category: 'computing',
    difficulty: 3,
    topicIds: ['data-structures', 'searching'],
  },
  {
    id: 'sigmoid',
    subjectId: 'ai',
    name: { ka: 'სიგმოიდური ფუნქცია' },
    expression: 'σ(x) = 1 / (1 + e⁻ˣ)',
    variables: [
      { symbol: 'x', meaning: { ka: 'შესატანი — ნეირონის „შეწონილი ჯამი"' } },
      { symbol: 'σ(x)', meaning: { ka: 'გამოსავალი 0-სა და 1-ს შორის' } },
      { symbol: 'e', meaning: { ka: 'ნატურალური ლოგარითმის ფუძე ≈ 2.718' } },
    ],
    explanation: {
      ka: 'სიგმოიდი ნებისმიერ ნამდვილ რიცხვს „ჩატენის" 0-სა და 1-ს შორის ინტერვალში, ამიტომ მისი გამოსავალი შეიძლება ალბათობად წავიკითხოთ. ის ერთ-ერთი პირველი არაწრფივი „აქტივაციის ფუნქციაა" ნეირონულ ქსელებში; დღეს ღრმა ქსელებში მას ხშირად ცვლის ReLU, რადგან სიგმოიდი ღრმა ფენებში „გრადიენტს ახრჩობს".',
    },
    example: { ka: 'σ(0) = 0.5;  σ(2) ≈ 0.88;  σ(−2) ≈ 0.12.' },
    category: 'computing',
    difficulty: 3,
    relatedFormulaIds: ['gradient-descent'],
    topicIds: ['neural-networks'],
  },
  {
    id: 'gradient-descent',
    subjectId: 'ai',
    name: { ka: 'გრადიენტული დაშვების ბიჯი' },
    expression: 'θ ← θ − η · ∇L(θ)',
    variables: [
      { symbol: 'θ', meaning: { ka: 'მოდელის პარამეტრები (წონები)' } },
      { symbol: 'η', meaning: { ka: 'სწავლის ტემპი — ბიჯის სიდიდე' } },
      { symbol: '∇L(θ)', meaning: { ka: 'დანაკარგის ფუნქციის გრადიენტი — მიმართულება, სადაც შეცდომა ყველაზე სწრაფად იზრდება' } },
    ],
    explanation: {
      ka: 'სწავლა ნიშნავს პარამეტრების ისეთ მნიშვნელობებს, სადაც შეცდომა (დანაკარგი) მინიმალურია. გრადიენტი გვიჩვენებს „აღმა" მიმართულებას, ამიტომ ბიჯს ვდგამთ საწინააღმდეგოდ. η-ს არჩევა კრიტიკულია: დიდი ბიჯი მინიმუმს გადააფრინდება, პატარა — ძალიან ნელა მიიყვანს.',
    },
    example: { ka: 'თუ η = 0.1 და ∇L = 4, პარამეტრი მცირდება 0.4-ით. ეს მეორდება მილიონობითჯერ.' },
    category: 'computing',
    difficulty: 4,
    relatedFormulaIds: ['sigmoid'],
    topicIds: ['neural-networks', 'training-vs-inference'],
  },
];

export const FORMULA_CATEGORY_LABELS: Record<string, { ka: string; en?: string }> = {
  mathematics: { ka: 'მათემატიკა', en: 'Mathematics' },
  physics: { ka: 'ფიზიკა', en: 'Physics' },
  chemistry: { ka: 'ქიმია', en: 'Chemistry' },
  statistics: { ka: 'სტატისტიკა', en: 'Statistics' },
  engineering: { ka: 'ინჟინერია', en: 'Engineering' },
  computing: { ka: 'გამოთვლა', en: 'Computing' },
};
