import type { Person } from './schema';

const brit = (label: string, slug: string) => ({
  label,
  publisher: 'Encyclopædia Britannica',
  url: `https://www.britannica.com/${slug}`,
  kind: 'encyclopedia' as const,
});

export const PEOPLE: Person[] = [
  {
    id: 'newton',
    subjectId: 'physics',
    name: { ka: 'ისააკ ნიუტონი', en: 'Isaac Newton' },
    lived: '1643–1727',
    known: { ka: 'მოძრაობის კანონები, მსოფლიო მიზიდულობა, კალკულუსი' },
    story: {
      ka: 'ნიუტონის მთავარი აღმოჩენა ის კი არ იყო, რომ საგნები ვარდება, არამედ რომ დედამიწაზე ვაშლის დაცემა და ცაში მთვარის ბრუნვა ერთი და იმავე კანონს ემორჩილება. მანამდე ითვლებოდა, რომ ცა და მიწა სხვადასხვა წესებით ცხოვრობდნენ. ჭირის გამო კემბრიჯის დახურვის ორ წელიწადში მან ერთდროულად შექმნა კალკულუსი, ჩამოაყალიბა ოპტიკის საფუძვლები და მიზიდულობის კანონი.',
    },
    topicIds: ['newton-laws', 'gravity'],
    sources: [brit('Isaac Newton', 'biography/Isaac-Newton')],
  },
  {
    id: 'einstein',
    subjectId: 'physics',
    name: { ka: 'ალბერტ აინშტაინი', en: 'Albert Einstein' },
    lived: '1879–1955',
    known: { ka: 'ფარდობითობის თეორია, ფოტოეფექტი' },
    story: {
      ka: '1905 წელს, პატენტების ბიუროში მუშაობისას, აინშტაინმა ოთხი სტატია გამოაქვეყნა, რომელთაგან თითოეულმა ფიზიკის ცალკე დარგი შეცვალა. ნობელის პრემია მან ფარდობითობისთვის კი არ მიიღო, არამედ ფოტოეფექტის ახსნისთვის — სწორედ ის იყო კვანტური ფიზიკის ერთ-ერთი პირველი ქვაკუთხედი.',
    },
    topicIds: ['relativity', 'quantum'],
    sources: [brit('Albert Einstein', 'biography/Albert-Einstein')],
  },
  {
    id: 'curie',
    subjectId: 'chemistry',
    name: { ka: 'მარი კიური', en: 'Marie Curie' },
    lived: '1867–1934',
    known: { ka: 'რადიოაქტიურობა, პოლონიუმი და რადიუმი' },
    story: {
      ka: 'ერთადერთი ადამიანი, რომელმაც ნობელის პრემია ორ სხვადასხვა საბუნებისმეტყველო მეცნიერებაში მიიღო — ფიზიკაში (1903) და ქიმიაში (1911). ტონობით მადნიდან მან ხელით გამოყო წამები გრამი რადიუმი. სწორედ ტერმინი „რადიოაქტიურობა" მას ეკუთვნის.',
    },
    topicIds: ['periodic-table'],
    sources: [brit('Marie Curie', 'biography/Marie-Curie')],
  },
  {
    id: 'darwin',
    subjectId: 'biology',
    name: { ka: 'ჩარლზ დარვინი', en: 'Charles Darwin' },
    lived: '1809–1882',
    known: { ka: 'ბუნებრივი გადარჩევით ევოლუციის თეორია' },
    story: {
      ka: 'დარვინმა „სახეობათა წარმოშობა" აღმოჩენიდან 20 წელზე მეტი ხნის შემდეგ გამოაქვეყნა — ის მტკიცებულებებს აგროვებდა და კრიტიკას ელოდა. მისი იდეა მარტივია: თუ შთამომავლები ერთმანეთისგან ოდნავ განსხვავდებიან და ზოგი მათგანი უკეთ გადარჩება, მაშინ თაობათა განმავლობაში სახეობა აუცილებლად შეიცვლება.',
    },
    topicIds: ['evolution'],
    sources: [brit('Charles Darwin', 'biography/Charles-Darwin')],
  },
  {
    id: 'mendeleev',
    subjectId: 'chemistry',
    name: { ka: 'დმიტრი მენდელეევი', en: 'Dmitri Mendeleev' },
    lived: '1834–1907',
    known: { ka: 'პერიოდული სისტემა' },
    story: {
      ka: 'მენდელეევის სიძლიერე ის კი არ იყო, რომ ელემენტები დაალაგა, არამედ ის, რომ ცარიელი უჯრები დატოვა და ჯერ უცნობი ელემენტების თვისებები იწინასწარმეტყველა. როცა გალიუმი აღმოაჩინეს და მისი სიმკვრივე პროგნოზს დაემთხვა, ცხრილი ჰიპოტეზიდან კანონად იქცა.',
    },
    topicIds: ['periodic-table'],
    sources: [brit('Dmitri Mendeleev', 'biography/Dmitri-Mendeleev')],
  },
  {
    id: 'lovelace',
    subjectId: 'cs',
    name: { ka: 'ადა ლავლეისი', en: 'Ada Lovelace' },
    lived: '1815–1852',
    known: { ka: 'პირველი ალგორითმი გამომთვლელი მანქანისთვის' },
    story: {
      ka: 'ბებიჯის ანალიტიკური მანქანის აღწერისას ლავლეისმა შენიშვნები დაურთო, რომლებიც თვით სტატიაზე გრძელი აღმოჩნდა. სწორედ იქ დაინახა მან ის, რაც სხვებმა ვერა: მანქანას შეეძლო არა მხოლოდ რიცხვების დამუშავება, არამედ ნებისმიერი სიმბოლოსი — მუსიკის ჩათვლით.',
    },
    topicIds: ['computing-history'],
    sources: [brit('Ada Lovelace', 'biography/Ada-Lovelace')],
  },
  {
    id: 'turing',
    subjectId: 'cs',
    name: { ka: 'ალან ტიურინგი', en: 'Alan Turing' },
    lived: '1912–1954',
    known: { ka: 'გამოთვლადობის თეორია, ტიურინგის მანქანა' },
    story: {
      ka: '1936 წელს, კომპიუტერების არსებობამდე, ტიურინგმა აღწერა აბსტრაქტული მანქანა და დაამტკიცა, რომ არსებობს ამოცანები, რომელთა ამოხსნაც არცერთ მანქანას შეუძლია. მეორე მსოფლიო ომის დროს მან ბლეჩლი-პარკში „ენიგმის" შიფრის გატეხვაზე იმუშავა.',
    },
    topicIds: ['computability', 'computing-history'],
    sources: [brit('Alan Turing', 'biography/Alan-Turing')],
  },
  {
    id: 'noether',
    subjectId: 'math',
    name: { ka: 'ემი ნეთერი', en: 'Emmy Noether' },
    lived: '1882–1935',
    known: { ka: 'ნეთერის თეორემა, აბსტრაქტული ალგებრა' },
    story: {
      ka: 'ნეთერის თეორემა ფიზიკის ერთ-ერთი ყველაზე ღრმა შედეგია: ყოველ სიმეტრიას შენახვის კანონი შეესაბამება. ის, რომ ფიზიკის კანონები დროში არ იცვლება, სწორედ ენერგიის შენახვას ნიშნავს. მან წლების განმავლობაში ხელფასის გარეშე ასწავლა, რადგან ქალს იმ დროს გერმანიაში პროფესორობის უფლება არ ჰქონდა.',
    },
    topicIds: ['energy'],
    sources: [brit('Emmy Noether', 'biography/Emmy-Noether')],
  },
  {
    id: 'ramanujan',
    subjectId: 'math',
    name: { ka: 'სრინივასა რამანუჯანი', en: 'Srinivasa Ramanujan' },
    lived: '1887–1920',
    known: { ka: 'რიცხვთა თეორია, უსასრულო მწკრივები' },
    story: {
      ka: 'თითქმის სრულიად თვითნასწავლი მათემატიკოსი ინდოეთიდან, რომელმაც ათასობით ფორმულა ჩაწერა — ხშირად დამტკიცების გარეშე. მისი ჩანაწერების ნაწილს მათემატიკოსები დღემდე იკვლევენ და ბევრი მათგანი მართებული აღმოჩნდა.',
    },
    topicIds: ['prime-numbers', 'infinity'],
    sources: [brit('Srinivasa Ramanujan', 'biography/Srinivasa-Ramanujan')],
  },
  {
    id: 'gauss',
    subjectId: 'math',
    name: { ka: 'კარლ ფრიდრიხ გაუსი', en: 'Carl Friedrich Gauss' },
    lived: '1777–1855',
    known: { ka: 'რიცხვთა თეორია, ნორმალური განაწილება, გეომეტრია' },
    story: {
      ka: 'გაუსს „მათემატიკოსთა მეფეს" უწოდებდნენ. 24 წლის ასაკში მან გამოაქვეყნა წიგნი, რომელმაც რიცხვთა თეორია დამოუკიდებელ დისციპლინად აქცია. ის ბევრ აღმოჩენას საერთოდ არ აქვეყნებდა — მიაჩნდა, რომ ჯერ საკმარისად დახვეწილი არ იყო.',
    },
    topicIds: ['prime-numbers', 'statistics-basics'],
    sources: [brit('Carl Friedrich Gauss', 'biography/Carl-Friedrich-Gauss')],
  },
  {
    id: 'archimedes',
    subjectId: 'math',
    name: { ka: 'არქიმედე', en: 'Archimedes' },
    lived: 'ძვ. წ. ~287–212',
    known: { ka: 'ამწევი ძალა, ბერკეტი, π-ს შეფასება' },
    story: {
      ka: 'არქიმედემ π ისე შეაფასა, რომ წრეში და წრის გარშემო სწორი მრავალკუთხედები ჩახატა და მათი პერიმეტრები დათვალა — 96-კუთხედამდე მივიდა და მიიღო, რომ π 3.1408-სა და 3.1429-ს შორისაა. ეს ზუსტად ის იდეაა, რასაც დღეს ზღვარს ვუწოდებთ.',
    },
    topicIds: ['pi'],
    sources: [brit('Archimedes', 'biography/Archimedes')],
  },
  {
    id: 'al-khwarizmi',
    subjectId: 'math',
    name: { ka: 'ალ-ხვარაზმი', en: 'Al-Khwarizmi' },
    lived: '~780–850',
    known: { ka: 'ალგებრა, ათობითი სისტემის გავრცელება' },
    story: {
      ka: 'სიტყვა „ალგებრა" მისი წიგნის სათაურიდან მოდის („ალ-ჯაბრ"), სიტყვა „ალგორითმი" კი — მისივე სახელიდან. მან ალგებრა ცალკე დისციპლინად ჩამოაყალიბა: არა კონკრეტული ამოცანების კრებულად, არამედ განტოლებათა სისტემატური ამოხსნის მეთოდად.',
    },
    topicIds: ['quadratic-equations'],
    sources: [brit('al-Khwarizmi', 'biography/al-Khwarizmi')],
  },
  {
    id: 'rutherford',
    subjectId: 'physics',
    name: { ka: 'ერნესტ რეზერფორდი', en: 'Ernest Rutherford' },
    lived: '1871–1937',
    known: { ka: 'ატომის ბირთვის აღმოჩენა' },
    story: {
      ka: 'ოქროს ფოლგის ცდაში α-ნაწილაკების უმეტესობა თავისუფლად გაიარა, მაგრამ ზოგიერთი მკვეთრად აირეკლა უკან. რეზერფორდის შედარებით, ეს იმას ჰგავდა, თითქოს ქაღალდის ცხვირსახოცში ნასროლი ჭურვი უკან დაბრუნებულიყო. აქედან დაასკვნა: ატომის მასა პაწაწინა, მკვრივ ბირთვშია მოქცეული.',
    },
    topicIds: ['atom-structure'],
    sources: [brit('Ernest Rutherford', 'biography/Ernest-Rutherford')],
  },
  {
    id: 'bohr',
    subjectId: 'physics',
    name: { ka: 'ნილს ბორი', en: 'Niels Bohr' },
    lived: '1885–1962',
    known: { ka: 'ატომის კვანტური მოდელი' },
    story: {
      ka: 'ბორმა ახსნა, რატომ არ ცვივა ელექტრონები ბირთვზე: მათ მხოლოდ გარკვეული, დისკრეტული ენერგიის დონეები აქვთ ნებადართული. სწორედ ამიტომ ასხივებს თითოეული ელემენტი მკაცრად განსაზღვრულ ფერებს — ეს ატომის „თითის ანაბეჭდია".',
    },
    topicIds: ['atom-structure', 'quantum'],
    sources: [brit('Niels Bohr', 'biography/Niels-Bohr')],
  },
  {
    id: 'franklin',
    subjectId: 'biology',
    name: { ka: 'როზალინდ ფრანკლინი', en: 'Rosalind Franklin' },
    lived: '1920–1958',
    known: { ka: 'დნმ-ის რენტგენოსტრუქტურული კვლევა' },
    story: {
      ka: 'ფრანკლინის „ფოტო 51" იყო ის მტკიცებულება, რომელმაც დნმ-ის ორმაგი სპირალის სტრუქტურა გამოააშკარავა. მისი მონაცემები უოტსონსა და კრიკს მისივე ნებართვის გარეშე გადაეცა. ის 37 წლის ასაკში გარდაიცვალა — ნობელის პრემიის გადაცემამდე ოთხი წლით ადრე.',
    },
    topicIds: ['dna'],
    sources: [brit('Rosalind Franklin', 'biography/Rosalind-Franklin')],
  },
  {
    id: 'hawking',
    subjectId: 'astronomy',
    name: { ka: 'სტივენ ჰოკინგი', en: 'Stephen Hawking' },
    lived: '1942–2018',
    known: { ka: 'ჰოკინგის გამოსხივება, შავი ხვრელების თერმოდინამიკა' },
    story: {
      ka: 'ჰოკინგმა აჩვენა, რომ შავი ხვრელები სრულიად „შავები" არ არიან: კვანტური ეფექტების გამო ისინი ძალიან სუსტად ასხივებენ და ძალიან ნელა აორთქლდებიან. ეს იყო პირველი სერიოზული ხიდი კვანტურ მექანიკასა და გრავიტაციას შორის.',
    },
    topicIds: ['black-holes'],
    sources: [brit('Stephen Hawking', 'biography/Stephen-Hawking')],
  },
  {
    id: 'hubble-person',
    subjectId: 'astronomy',
    name: { ka: 'ედვინ ჰაბლი', en: 'Edwin Hubble' },
    lived: '1889–1953',
    known: { ka: 'გალაქტიკების აღმოჩენა, სამყაროს გაფართოება' },
    story: {
      ka: '1920-იან წლებამდე ითვლებოდა, რომ მთელი სამყარო ჩვენი გალაქტიკა იყო. ჰაბლმა ანდრომედაში ცვალებადი ვარსკვლავები დაინახა და დაამტკიცა, რომ ის ჩვენგან ძალიან შორსაა — ანუ ცალკე გალაქტიკაა. ერთი დაკვირვებით სამყარო მილიარდჯერ გაფართოვდა.',
    },
    topicIds: ['cosmology', 'galaxies'],
    sources: [brit('Edwin Hubble', 'biography/Edwin-Hubble')],
  },
  {
    id: 'shannon',
    subjectId: 'cs',
    name: { ka: 'კლოდ შენონი', en: 'Claude Shannon' },
    lived: '1916–2001',
    known: { ka: 'ინფორმაციის თეორია' },
    story: {
      ka: '1948 წელს შენონმა ერთი სტატიით შექმნა ინფორმაციის თეორია და შემოიღო სიტყვა „ბიტი". მისი მთავარი იდეა: ინფორმაცია შეიძლება გაიზომოს, მიუხედავად იმისა, ტექსტია ის, სურათი თუ ხმა. ყოველი ინტერნეტკავშირი დღეს მის ფორმულებს ეყრდნობა.',
    },
    topicIds: ['information-theory'],
    sources: [brit('Claude Shannon', 'biography/Claude-Shannon')],
  },
  {
    id: 'hopper',
    subjectId: 'cs',
    name: { ka: 'გრეის ჰოპერი', en: 'Grace Hopper' },
    lived: '1906–1992',
    known: { ka: 'პირველი კომპილატორი, COBOL' },
    story: {
      ka: 'ჰოპერი იმას ამტკიცებდა, რასაც მაშინ თითქმის არავინ იჯერებდა: პროგრამა შეიძლება ადამიანურ ენასთან ახლოს დაიწეროს და მანქანამ თვითონ თარგმნოს. სწორედ ეს იდეაა დღეს ყველა პროგრამირების ენის საფუძველი.',
    },
    topicIds: ['computing-history'],
    sources: [brit('Grace Hopper', 'biography/Grace-Hopper')],
  },
  {
    id: 'feynman',
    subjectId: 'physics',
    name: { ka: 'რიჩარდ ფაინმანი', en: 'Richard Feynman' },
    lived: '1918–1988',
    known: { ka: 'კვანტური ელექტროდინამიკა, ფაინმანის დიაგრამები' },
    story: {
      ka: 'ფაინმანი ამბობდა, რომ თუ ვერ ახსნი მარტივად, ესე იგი ბოლომდე ვერ გაიგე. მისი დიაგრამები ნაწილაკების ურთიერთქმედების უმძიმეს გამოთვლებს თითქმის სურათებად აქცევს — ეს დღეს ნაწილაკთა ფიზიკის სტანდარტული ენაა.',
    },
    topicIds: ['quantum'],
    sources: [brit('Richard Feynman', 'biography/Richard-Feynman')],
  },
  {
    id: 'muskhelishvili',
    subjectId: 'math',
    name: { ka: 'ნიკოლოზ მუსხელიშვილი', en: 'Nikoloz Muskhelishvili' },
    lived: '1891–1976',
    known: { ka: 'დრეკადობის მათემატიკური თეორია, ინტეგრალური განტოლებები' },
    story: {
      ka: 'მუსხელიშვილის ნაშრომებმა კომპლექსური ანალიზი დრეკადობის თეორიის ამოცანების გადასაწყვეტად გამოიყენა — მეთოდი, რომელიც დღემდე ისწავლება მთელ მსოფლიოში. ის საქართველოს მეცნიერებათა აკადემიის პირველი პრეზიდენტი იყო.',
    },
    sources: [
      {
        label: 'ნიკოლოზ მუსხელიშვილი',
        publisher: 'MacTutor History of Mathematics Archive, University of St Andrews',
        url: 'https://mathshistory.st-andrews.ac.uk/Biographies/Muskhelishvili/',
        kind: 'institution',
      },
    ],
  },
  {
    id: 'vekua',
    subjectId: 'math',
    name: { ka: 'ილია ვეკუა', en: 'Ilia Vekua' },
    lived: '1907–1977',
    known: { ka: 'განზოგადებული ანალიზური ფუნქციები, გარსების თეორია' },
    story: {
      ka: 'ვეკუამ განავითარა განზოგადებული ანალიზური ფუნქციების თეორია, რომელიც კერძოწარმოებულებიან განტოლებებში გამოიყენება. ის თბილისის სახელმწიფო უნივერსიტეტის რექტორი იყო და ნოვოსიბირსკის სახელმწიფო უნივერსიტეტის პირველი რექტორიც.',
    },
    sources: [
      {
        label: 'ილია ვეკუა',
        publisher: 'MacTutor History of Mathematics Archive, University of St Andrews',
        url: 'https://mathshistory.st-andrews.ac.uk/Biographies/Vekua/',
        kind: 'institution',
      },
    ],
  },
  {
    id: 'rustaveli',
    subjectId: 'georgian-literature',
    name: { ka: 'შოთა რუსთაველი', en: 'Shota Rustaveli' },
    lived: 'XII–XIII საუკუნეები',
    known: { ka: '„ვეფხისტყაოსანი"' },
    story: {
      ka: '„ვეფხისტყაოსანი" თამარ მეფის ეპოქაში დაიწერა და ქართული ლიტერატურის ცენტრალური ტექსტია. პოემა შაირით — თექვსმეტმარცვლიანი საზომით — არის დაწერილი და მისი ბევრი სტრიქონი დღემდე ცოცხალ სასაუბრო ქართულში გამოიყენება.',
    },
    topicIds: ['vepkhistqaosani'],
    sources: [brit('Shota Rustaveli', 'biography/Shota-Rustaveli')],
  },
  {
    id: 'ilia-chavchavadze',
    subjectId: 'georgian-literature',
    name: { ka: 'ილია ჭავჭავაძე', en: 'Ilia Chavchavadze' },
    lived: '1837–1907',
    known: { ka: 'მწერალი, პუბლიცისტი, საზოგადო მოღვაწე' },
    story: {
      ka: 'ილია ჭავჭავაძე XIX საუკუნის ქართული ეროვნული მოძრაობის ცენტრალური ფიგურა იყო. მან გაზეთებისა და ლიტერატურის საშუალებით ენისა და განათლების საკითხი საზოგადოებრივი ცხოვრების ცენტრში დააყენა.',
    },
    sources: [brit('Ilia Chavchavadze', 'biography/Ilia-Chavchavadze')],
  },
  {
    id: 'vakhushti',
    subjectId: 'georgian-history',
    name: { ka: 'ვახუშტი ბაგრატიონი', en: 'Vakhushti Bagrationi' },
    lived: '1696–1757',
    known: { ka: 'ისტორიკოსი და გეოგრაფი, საქართველოს რუკები' },
    story: {
      ka: 'ვახუშტიმ შექმნა საქართველოს პირველი სისტემატური გეოგრაფიული აღწერა და დეტალური რუკები. მისი ნაშრომი „აღწერა სამეფოსა საქართველოსა" დღემდე ისტორიკოსების ერთ-ერთი მთავარი წყაროა.',
    },
    sources: [
      {
        label: 'ვახუშტი ბაგრატიონი — ეროვნული ბიბლიოთეკის ციფრული კოლექცია',
        publisher: 'საქართველოს პარლამენტის ეროვნული ბიბლიოთეკა',
        url: 'http://www.nplg.gov.ge/',
        kind: 'institution',
      },
    ],
  },

  /* ------------------------- ინფორმატიკა ------------------------- */
  {
    id: 'knuth',
    subjectId: 'cs',
    name: { ka: 'დონალდ კნუტი', en: 'Donald Knuth' },
    lived: '1938 —',
    known: { ka: '„The Art of Computer Programming", ალგორითმების ანალიზი, TeX' },
    story: {
      ka: 'კნუტმა ალგორითმების შესწავლა ზუსტ მეცნიერებად აქცია — მკაცრი მათემატიკური ანალიზით იმისა, რამდენ ნაბიჯს მოითხოვს პროგრამა. 1962 წელს დაწყებული წიგნი „The Art of Computer Programming" დღემდე არ დაუსრულებია. როცა ტიპოგრაფიის ხარისხმა იმედი გაუცრუა, შეაჩერა მთავარი საქმე და ათ წელიწადში შექმნა TeX — სისტემა, რომლითაც დღემდე იწყობა მეცნიერული ტექსტების უმეტესობა. მისი ცნობილი ფრაზაა: „ნაადრევი ოპტიმიზაცია ყოველგვარი ბოროტების ფესვია".',
    },
    topicIds: ['algorithm-complexity', 'searching', 'sorting-algorithms', 'computing-history'],
    sources: [brit('Donald Knuth', 'biography/Donald-Knuth')],
  },
  {
    id: 'dijkstra',
    subjectId: 'algorithms',
    name: { ka: 'ედსხერ დაიქსტრა', en: 'Edsger Dijkstra' },
    lived: '1930–2002',
    known: { ka: 'უმოკლესი გზის ალგორითმი, სტრუქტურული პროგრამირება' },
    story: {
      ka: 'დაიქსტრამ უმოკლესი გზის ცნობილი ალგორითმი 1956 წელს, კაფეში ჯდომისას, 20 წუთში მოიფიქრა. 1968 წლის წერილმა „Go To Statement Considered Harmful" დაიწყო სტრუქტურული პროგრამირების მოძრაობა. ის ამტკიცებდა, რომ პროგრამირება მათემატიკური დისციპლინაა და კოდი ისე უნდა დაიწეროს, რომ მისი სისწორის დამტკიცება შესაძლებელი იყოს.',
    },
    topicIds: ['graphs-and-paths', 'control-flow', 'algorithm-complexity'],
    sources: [brit('Edsger Dijkstra', 'biography/Edsger-Dijkstra')],
  },
  {
    id: 'hoare',
    subjectId: 'algorithms',
    name: { ka: 'ტონი ჰოარი', en: 'Tony Hoare' },
    lived: '1934 —',
    known: { ka: 'Quicksort, პროგრამების ლოგიკური ვერიფიკაცია' },
    story: {
      ka: 'ჰოარმა Quicksort 1959 წელს, 25 წლის ასაკში, მოსკოვში მთარგმნელობით პროექტზე მუშაობისას შექმნა. მოგვიანებით მან შეიმუშავა „ჰოარის ლოგიკა" — ფორმალური სისტემა პროგრამის სისწორის დასამტკიცებლად. 2009 წელს მან „null მიმართვას" საკუთარი „მილიარდ-დოლარიანი შეცდომა" უწოდა: 1965 წელს ის მარტივი ჩანდა, სინამდვილეში კი ათწლეულების განმავლობაში უამრავი ავარიისა და უსაფრთხოების ხვრელის მიზეზი გახდა.',
    },
    topicIds: ['sorting-algorithms', 'bugs-and-debugging', 'data-structures'],
    sources: [brit('Tony Hoare', 'biography/Tony-Hoare')],
  },
  {
    id: 'ritchie',
    subjectId: 'programming',
    name: { ka: 'დენის რიჩი', en: 'Dennis Ritchie' },
    lived: '1941–2011',
    known: { ka: 'ენა C, ოპერაციული სისტემა Unix (კენ ტომფსონთან ერთად)' },
    story: {
      ka: 'რიჩიმ 1972 წელს Bell Labs-ში შექმნა ენა C — საკმარისად დაბალი დონისა, რომ ოპერაციული სისტემა დაწერო, საკმარისად მაღლისა, რომ ის ერთი მანქანიდან მეორეზე გადაიტანო. კენ ტომფსონთან ერთად მან C-ზე გადაწერა Unix. დღეს C-ისა და Unix-ის შთამომავლები (Linux, macOS, Android) პლანეტის კომპიუტერების უმეტესობას ამუშავებს.',
    },
    topicIds: ['how-code-runs', 'computing-history'],
    sources: [brit('Dennis Ritchie', 'biography/Dennis-Ritchie')],
  },
  {
    id: 'torvalds',
    subjectId: 'programming',
    name: { ka: 'ლინუს ტორვალდსი', en: 'Linus Torvalds' },
    lived: '1969 —',
    known: { ka: 'Linux-ის ბირთვი, ვერსიების კონტროლის სისტემა Git' },
    story: {
      ka: '1991 წელს, ჰელსინკის უნივერსიტეტის სტუდენტმა, ტორვალდსმა დაიწყო თავისუფალი ოპერაციული სისტემის ბირთვის წერა — „მხოლოდ ჰობი, არაფერი სერიოზული". დღეს Linux ამუშავებს სერვერების, სუპერკომპიუტერებისა და Android-ტელეფონების უმეტესობას. 2005 წელს, როცა Linux-ის გუნდმა დაკარგა წვდომა ვერსიების კონტროლის ხელსაწყოზე, ტორვალდსმა ორ კვირაში დაწერა Git.',
    },
    topicIds: ['version-control', 'how-code-runs'],
    sources: [brit('Linus Torvalds', 'biography/Linus-Torvalds')],
  },
  {
    id: 'berners-lee',
    subjectId: 'cs',
    name: { ka: 'ტიმ ბერნერს-ლი', en: 'Tim Berners-Lee' },
    lived: '1955 —',
    known: { ka: 'World Wide Web — HTTP, HTML, URL' },
    story: {
      ka: '1989 წელს CERN-ში ბერნერს-ლიმ შემოგვთავაზა სისტემა, სადაც დოკუმენტები ერთმანეთს ბმულებით უკავშირდებოდა ინტერნეტის გავლით. მან დაწერა პირველი ბრაუზერი, სერვერი და გვერდი. 1993 წელს CERN-მა ვების ტექნოლოგია საჯარო, უფასო სარგებლობაში გადასცა — ეს გადაწყვეტილება იყო მიზეზი, რატომ გახდა ვები საყოველთაო და არა ერთი კომპანიის საკუთრება.',
    },
    topicIds: ['networks', 'computing-history'],
    sources: [brit('Tim Berners-Lee', 'biography/Tim-Berners-Lee')],
  },
  {
    id: 'mccarthy',
    subjectId: 'ai',
    name: { ka: 'ჯონ მაკკარტი', en: 'John McCarthy' },
    lived: '1927–2011',
    known: { ka: 'ტერმინი „ხელოვნური ინტელექტი", ენა Lisp' },
    story: {
      ka: 'მაკკარტიმ ტერმინი „artificial intelligence" 1955 წელს შემოიღო დარტმუთის სემინარის განაცხადში — შეხვედრისა, რომელიც დარგის დაბადებად ითვლება. 1958 წელს მან შექმნა Lisp, სადაც პროგრამა და მონაცემი ერთი ფორმისაა და რეკურსია ენის გულია. Lisp-ის იდეები (ნაგვის ავტომატური შეგროვება, პირველი კლასის ფუნქციები) დღეს თითქმის ყველა თანამედროვე ენაშია.',
    },
    topicIds: ['what-is-machine-learning', 'functions-and-abstraction', 'programming-paradigms'],
    sources: [brit('John McCarthy', 'biography/John-McCarthy')],
  },
  {
    id: 'hinton',
    subjectId: 'ai',
    name: { ka: 'ჯეფრი ჰინტონი', en: 'Geoffrey Hinton' },
    lived: '1947 —',
    known: { ka: 'უკუგავრცელება, ღრმა სწავლება; ფიზიკის ნობელი 2024' },
    story: {
      ka: 'ჰინტონმა ათწლეულების განმავლობაში მაშინ განაგრძობდა ნეირონულ ქსელებზე მუშაობას, როცა დარგი მათ „ჩიხად" თვლიდა. 1986 წელს მან და კოლეგებმა გაავრცელეს უკუგავრცელების ალგორითმი; 2012 წელს მისი სტუდენტების ქსელმა (AlexNet) ImageNet-ის კონკურსი მოიგო და ღრმა სწავლების ეპოქა დაიწყო. 2024 წელს მიიღო ფიზიკის ნობელის პრემია. მას შემდეგ ის საჯაროდ საუბრობს AI-ის რისკებზე.',
    },
    topicIds: ['neural-networks', 'large-language-models', 'what-is-machine-learning'],
    sources: [
      {
        label: 'Geoffrey Hinton — Facts, Nobel Prize in Physics 2024',
        publisher: 'The Nobel Foundation',
        url: 'https://www.nobelprize.org/prizes/physics/2024/hinton/facts/',
        kind: 'institution',
      },
    ],
  },

  /* ------------------------- ფილოსოფია და საზოგადოება ------------------------- */
  {
    id: 'aristotle',
    subjectId: 'philosophy',
    name: { ka: 'არისტოტელე', en: 'Aristotle' },
    lived: 'ძვ. წ. 384–322',
    known: { ka: 'ლოგიკა, ეთიკა, ბიოლოგია, პოეტიკა' },
    story: {
      ka: 'არისტოტელემ დააფუძნა ფორმალური ლოგიკა (სილოგიზმი) და დაწერა პირველი სისტემური ტრაქტატები თითქმის ყველა დარგზე — ფიზიკიდან თეატრის თეორიამდე. მისი მიდგომა — დააკვირდი, დააჯგუფე, ახსენი — მეცნიერული მეთოდის ერთ-ერთი ფესვია. ორი ათასი წლის განმავლობაში ევროპულ უნივერსიტეტებში „ფილოსოფოსი" ნიშნავდა უბრალოდ არისტოტელეს.',
    },
    topicIds: ['logic-and-arguments', 'ethics-frameworks', 'tragedy-and-theatre'],
    sources: [brit('Aristotle', 'biography/Aristotle')],
  },
  {
    id: 'descartes',
    subjectId: 'philosophy',
    name: { ka: 'რენე დეკარტი', en: 'René Descartes' },
    lived: '1596–1650',
    known: { ka: 'რაციონალიზმი, ანალიზური გეომეტრია, „ვფიქრობ, მაშ ვარსებობ"' },
    story: {
      ka: 'დეკარტმა სცადა ცოდნის აგება ნულიდან: ყველაფერში დაეჭვება, სანამ არ იპოვიდა რაღაცას, რაშიც ეჭვი შეუძლებელი იყო — და ეს იყო თავად ეჭვის მქონე „მე". ის ასევე მათემატიკოსი იყო: მან გააერთიანა ალგებრა და გეომეტრია კოორდინატთა სისტემით, რომელსაც დღემდე „დეკარტისეულს" ვუწოდებთ.',
    },
    topicIds: ['theory-of-knowledge'],
    sources: [brit('René Descartes', 'biography/Rene-Descartes')],
  },
  {
    id: 'kant',
    subjectId: 'philosophy',
    name: { ka: 'იმანუელ კანტი', en: 'Immanuel Kant' },
    lived: '1724–1804',
    known: { ka: 'კატეგორიული იმპერატივი, „წმინდა გონების კრიტიკა"' },
    story: {
      ka: 'კანტმა სცადა შეერიგებინა რაციონალიზმი და ემპირიზმი: გონება არ არის ცარიელი ფურცელი და არც სამყაროს პასიური სარკე — ის აქტიურად „აწყობს" გამოცდილებას თანდაყოლილი ფორმებით. ეთიკაში მან ჩამოაყალიბა წესი: იმოქმედე მხოლოდ ისე, როგორც გინდოდა, რომ ყველა მოქცეულიყო.',
    },
    topicIds: ['ethics-frameworks'],
    sources: [brit('Immanuel Kant', 'biography/Immanuel-Kant')],
  },
  {
    id: 'montesquieu',
    subjectId: 'civics',
    name: { ka: 'შარლ დე მონტესკიე', en: 'Montesquieu' },
    lived: '1689–1755',
    known: { ka: 'ხელისუფლების დანაწილების თეორია' },
    story: {
      ka: '1748 წელს ნაშრომში „კანონთა შესახებ" მონტესკიემ ამტკიცა, რომ თავისუფლების დაცვის საუკეთესო გზა ძალაუფლების სამ შტოდ დაყოფაა, სადაც თითოეული აკავებს დანარჩენებს. ეს იდეა თითქმის პირდაპირ შევიდა აშშ-ის კონსტიტუციაში და დღეს დემოკრატიული წყობის საზომია.',
    },
    topicIds: ['separation-of-powers'],
    sources: [brit('Montesquieu', 'biography/Montesquieu')],
  },
  {
    id: 'adam-smith',
    subjectId: 'economics',
    name: { ka: 'ადამ სმიტი', en: 'Adam Smith' },
    lived: '1723–1790',
    known: { ka: '„ერთა სიმდიდრე", „უხილავი ხელი", შრომის დანაწილება' },
    story: {
      ka: 'სმიტი მორალის ფილოსოფოსი იყო, სანამ ეკონომისტი გახდებოდა. 1776 წელს „ერთა სიმდიდრეში" მან აჩვენა, როგორ შეიძლება პირადი ინტერესით მოქმედი ადამიანების ქმედება, კონკურენციის პირობებში, საერთო კეთილდღეობას ემსახურებოდეს — მაგრამ ის ასევე აფრთხილებდა მონოპოლიისა და ვაჭართა ლობის საფრთხეზე.',
    },
    topicIds: ['scarcity-opportunity-cost', 'supply-demand-prices'],
    sources: [brit('Adam Smith', 'biography/Adam-Smith')],
  },
  {
    id: 'kahneman',
    subjectId: 'psychology',
    name: { ka: 'დანიელ კანემანი', en: 'Daniel Kahneman' },
    lived: '1934–2024',
    known: { ka: 'ქცევითი ეკონომიკა, კოგნიტური მიკერძოებები' },
    story: {
      ka: 'კანემანმა და ამოს ტვერსკიმ 1970-იან წლებში აჩვენეს, რომ ადამიანის მსჯელობა სისტემურად, პროგნოზირებადად გადაუხვევს რაციონალურ მოდელს. ამ ნაშრომმა შექმნა ქცევითი ეკონომიკა. 2002 წელს კანემანმა ეკონომიკის ნობელის პრემია მიიღო — თუმცა ის ფსიქოლოგი იყო და არასდროს გაუვლია ეკონომიკის კურსი.',
    },
    topicIds: ['cognitive-biases'],
    sources: [brit('Daniel Kahneman', 'biography/Daniel-Kahneman')],
  },
  {
    id: 'pavlov',
    subjectId: 'psychology',
    name: { ka: 'ივან პავლოვი', en: 'Ivan Pavlov' },
    lived: '1849–1936',
    known: { ka: 'კლასიკური დაჯერება' },
    story: {
      ka: 'პავლოვი საჭმლის მონელების ფიზიოლოგიას იკვლევდა, როცა შეამჩნია, რომ ძაღლები ნერწყვდებოდნენ ჯერ კიდევ საკვების დანახვამდე — ლაბორანტის ნაბიჯების ხმაზეც კი. ამ შემთხვევითმა დაკვირვებამ სწავლის ერთ-ერთი ფუნდამენტური მექანიზმი გამოავლინა. 1904 წელს მიიღო ფიზიოლოგიის ნობელის პრემია.',
    },
    topicIds: ['conditioning-and-learning'],
    sources: [brit('Ivan Pavlov', 'biography/Ivan-Pavlov')],
  },
  {
    id: 'loftus',
    subjectId: 'psychology',
    name: { ka: 'ელიზაბეტ ლოფტუსი', en: 'Elizabeth Loftus' },
    lived: '1944 —',
    known: { ka: 'მეხსიერების რეკონსტრუქციული ბუნება, ცრუ მოგონებები' },
    story: {
      ka: 'ლოფტუსის ექსპერიმენტებმა აჩვენა, რომ კითხვის ფორმულირებაც კი ცვლის მოწმის „მოგონებას", და რომ ადამიანებს შესაძლებელია ჩაენერგოთ მთელი მოვლენების ცრუ, მაგრამ ცხადი მოგონებები. მისმა კვლევამ პირდაპირ იმოქმედა სასამართლო პრაქტიკაზე — მოწმის ჩვენების სანდოობის შეფასებაზე.',
    },
    topicIds: ['memory-and-forgetting'],
    sources: [brit('Elizabeth Loftus', 'biography/Elizabeth-Loftus')],
  },

  /* ------------------------- ლიტერატურა და ხელოვნება ------------------------- */
  {
    id: 'homer',
    subjectId: 'world-literature',
    name: { ka: 'ჰომეროსი', en: 'Homer' },
    lived: '≈ ძვ. წ. VIII საუკუნე',
    known: { ka: '„ილიადა", „ოდისეა"' },
    story: {
      ka: '„ჰომეროსი" შესაძლოა ერთი პოეტი კი არ იყოს, არამედ ზეპირი ტრადიციის სახელი. „ილიადისა" და „ოდისეის" ფორმულური სტილი — გამეორებადი ეპითეტები და ფრაზები — ცოცხალი ზეპირი კომპოზიციის კვალია. ეს პოემები დასავლური ლიტერატურის საწყისად ითვლება.',
    },
    topicIds: ['epic-and-oral-tradition'],
    sources: [brit('Homer', 'biography/Homer-Greek-poet')],
  },
  {
    id: 'cervantes',
    subjectId: 'world-literature',
    name: { ka: 'მიგელ დე სერვანტესი', en: 'Miguel de Cervantes' },
    lived: '1547–1616',
    known: { ka: '„დონ კიხოტი"' },
    story: {
      ka: 'სერვანტესმა ცხოვრების დიდი ნაწილი გაჭირვებაში გაატარა — ის იყო ჯარისკაცი, ტყვე ალჟირში, გადასახადების ამკრეფი. „დონ კიხოტი" (1605/1615) რაინდულ რომანებს დასცინის, მაგრამ იმდენად ღრმად, რომ თავად გახდა პირველი თანამედროვე რომანი: პერსონაჟი იცვლება, თხრობა თავად ხდება თემა.',
    },
    topicIds: ['birth-of-the-novel'],
    sources: [brit('Miguel de Cervantes', 'biography/Miguel-de-Cervantes')],
  },
  {
    id: 'shakespeare',
    subjectId: 'world-literature',
    name: { ka: 'უილიამ შექსპირი', en: 'William Shakespeare' },
    lived: '1564–1616',
    known: { ka: 'ტრაგედიები, კომედიები, სონეტები' },
    story: {
      ka: 'შექსპირმა ინგლისური დრამა გაათავისუფლა კლასიკური წესებისგან და შუაში დააყენა პერსონაჟის შინაგანი ცხოვრება — „ჰამლეტის" მოქმედების დიდი ნაწილი გმირის თავშია. მას ინგლისურ ენაში ასობით გამოთქმა და ≈ 1700 სიტყვის პირველი წერილობითი ხმარება მიეწერება.',
    },
    topicIds: ['tragedy-and-theatre'],
    sources: [brit('William Shakespeare', 'biography/William-Shakespeare')],
  },
  {
    id: 'akaki-tsereteli',
    subjectId: 'georgian-literature',
    name: { ka: 'აკაკი წერეთელი', en: 'Akaki Tsereteli' },
    lived: '1840–1915',
    known: { ka: 'პოეზია, „სულიკო", ეროვნული მოძრაობა' },
    story: {
      ka: 'აკაკი თერგდალეულთა თაობის პოეტური ხმა იყო. მისი ლექსები — მათ შორის „სულიკო" — სიმღერებად იქცა და ეროვნული სენტიმენტის ცოცხალ ნაწილად დარჩა. ილიასთან ერთად ის XIX საუკუნის ბოლოს ქართული საზოგადოებრივი ცხოვრების ცენტრში იდგა.',
    },
    topicIds: ['tergdaleulebi'],
    sources: [brit('Akaki Tsereteli', 'biography/Akaki-Tsereteli')],
  },
  {
    id: 'galaktion',
    subjectId: 'georgian-literature',
    name: { ka: 'გალაკტიონ ტაბიძე', en: 'Galaktion Tabidze' },
    lived: '1892–1959',
    known: { ka: 'XX საუკუნის ქართული პოეზიის ცენტრალური ფიგურა' },
    story: {
      ka: 'გალაკტიონმა ქართული ლექსის მუსიკალობა ახალ დონეზე აიყვანა. საბჭოთა პერიოდში ის ოფიციალურად აღიარებული „ხალხის პოეტი" იყო, თუმცა მისი პირადი დღიურები და მრავალი ტექსტი მხოლოდ დამოუკიდებლობის შემდეგ გამოქვეყნდა სრულად. 1959 წელს ფსიქიატრიულ საავადმყოფოში დაასრულა სიცოცხლე.',
    },
    topicIds: ['twentieth-century-georgian-poetry'],
    sources: [
      {
        label: 'გალაკტიონ ტაბიძე — ცხოვრება და შემოქმედება',
        publisher: 'საქართველოს პარლამენტის ეროვნული ბიბლიოთეკა',
        url: 'http://www.nplg.gov.ge/',
        kind: 'institution',
      },
    ],
  },
  {
    id: 'pirosmani',
    subjectId: 'art-history',
    name: { ka: 'ნიკო ფიროსმანი', en: 'Niko Pirosmani' },
    lived: '1862–1918',
    known: { ka: 'თვითნასწავლი მხატვარი, ქართული „პრიმიტივიზმი"' },
    story: {
      ka: 'ფიროსმანი დუქნებს უხატავდა ულუფა საჭმლისა და თავშესაფრის სანაცვლოდ. მისი ნახატები — შავ ფონზე, პირდაპირი, მონუმენტური ფიგურებით — ევროპულმა ავანგარდმა 1913 წელს „აღმოაჩინა". ის სიღარიბეში გარდაიცვალა, აღიარება კი მხოლოდ სიკვდილის შემდეგ ეწია; დღეს ის ქართული ვიზუალური იდენტობის სიმბოლოა.',
    },
    topicIds: ['georgian-visual-tradition', 'representation-to-abstraction'],
    sources: [brit('Niko Pirosmani', 'biography/Niko-Pirosmani')],
  },

  /* ------------------------- საქართველოს ისტორია ------------------------- */
  {
    id: 'david-aghmashenebeli',
    subjectId: 'georgian-history',
    name: { ka: 'დავით IV აღმაშენებელი', en: 'David IV the Builder' },
    lived: '1073–1125',
    known: { ka: 'საქართველოს გამაერთიანებელი, დიდგორის ბრძოლა' },
    story: {
      ka: '16 წლისა გამეფებულმა დავითმა დაქუცმაცებული, სელჩუკებისგან აოხრებული ქვეყანა ერთ საუკუნეში კავკასიის უძლიერეს სახელმწიფოდ აქცია. მან შექმნა მუდმივი არმია, მოახდინა ეკლესიის რეფორმა, დააარსა გელათის აკადემია. 1121 წელს დიდგორთან გაცილებით მრავალრიცხოვანი მოწინააღმდეგე დაამარცხა და თბილისი გაათავისუფლა. ქართული ეკლესიის წმინდანია.',
    },
    topicIds: ['georgian-golden-age'],
    sources: [brit('David IV', 'biography/David-IV-Aghmashenebeli')],
  },
  {
    id: 'tamar-mepe',
    subjectId: 'georgian-history',
    name: { ka: 'მეფე თამარი', en: 'Tamar of Georgia' },
    lived: '≈ 1160–1213',
    known: { ka: 'ოქროს ხანის მწვერვალი; „მეფე", არა „დედოფალი"' },
    story: {
      ka: 'თამარის მმართველობა (1184–1213) საქართველოს ისტორიის ყველაზე გავლენიან პერიოდად ითვლება: შიდაპოლიტიკური კონსოლიდაცია, გავლენის გავრცელება შირვანზე და ტრაპიზონზე, ბასიანის ბრძოლა. მის ეპოქაში აშენდა ვარძია, მოიჭრა ქართული მონეტა და დაიწერა „ვეფხისტყაოსანი". ის ქართული ეკლესიის წმინდანია.',
    },
    topicIds: ['georgian-golden-age'],
    sources: [brit('Tamar', 'biography/Tamar')],
  },
  {
    id: 'erekle-mepe',
    subjectId: 'georgian-history',
    name: { ka: 'ერეკლე II', en: 'Erekle II' },
    lived: '1720–1798',
    known: { ka: 'ქართლ-კახეთის მეფე, გეორგიევსკის ტრაქტატი' },
    story: {
      ka: 'ერეკლემ გააერთიანა ქართლი და კახეთი და ცდილობდა დაქუცმაცებული ქვეყნის გაძლიერებას ორ მუსლიმურ იმპერიას შორის. 1783 წელს დადო გეორგიევსკის ტრაქტატი რუსეთთან მფარველობის იმედით, მაგრამ 1795 წელს, კრწანისის ბრძოლის შემდეგ, სპარსეთის შაჰმა თბილისი მაინც გადაწვა — რუსული დახმარება არ მოვიდა.',
    },
    topicIds: ['georgian-fragmentation'],
    sources: [brit('Georgia — History', 'place/Georgia/History')],
  },
  {
    id: 'noe-jordania',
    subjectId: 'georgian-history',
    name: { ka: 'ნოე ჟორდანია', en: 'Noe Zhordania' },
    lived: '1868–1953',
    known: { ka: 'საქართველოს დემოკრატიული რესპუბლიკის მთავრობის მეთაური' },
    story: {
      ka: 'ჟორდანია ქართული სოციალ-დემოკრატიის (მენშევიზმის) ლიდერი იყო. 1918–1921 წლებში ის ხელმძღვანელობდა დამოუკიდებელი საქართველოს მთავრობას, რომელმაც მიწის რეფორმა და ქალთა ხმის უფლება გაატარა. 1921 წლის საბჭოთა შემოსევის შემდეგ მთავრობა საფრანგეთში გადავიდა, სადაც ჟორდანია ემიგრაციაში გარდაიცვალა.',
    },
    topicIds: ['first-republic-1918'],
    sources: [
      {
        label: 'საქართველოს დემოკრატიული რესპუბლიკა 1918–1921',
        publisher: 'საქართველოს პარლამენტის ეროვნული ბიბლიოთეკა',
        url: 'http://www.nplg.gov.ge/',
        kind: 'institution',
      },
    ],
  },
  {
    id: 'zviad-gamsakhurdia',
    subjectId: 'georgian-history',
    name: { ka: 'ზვიად გამსახურდია', en: 'Zviad Gamsakhurdia' },
    lived: '1939–1993',
    known: { ka: 'დისიდენტი, საქართველოს პირველი პრეზიდენტი' },
    story: {
      ka: 'გამსახურდია საბჭოთა პერიოდში ცნობილი დისიდენტი და ადამიანის უფლებათა დამცველი იყო. 1990 წელს მისმა ბლოკმა მოიგო არჩევნები, 1991 წლის აპრილში კი პარლამენტმა დამოუკიდებლობა გამოაცხადა. მალევე დაწყებულმა შიდაპოლიტიკურმა დაპირისპირებამ 1992 წელს მისი ჩამოგდება გამოიწვია; ის 1993 წელს გარდაიცვალა.',
    },
    topicIds: ['soviet-georgia-independence'],
    sources: [brit('Zviad Gamsakhurdia', 'biography/Zviad-Gamsakhurdia')],
  },
];
