import type { Subject } from './schema';

/**
 * The initial lab set. This list is deliberately *not* treated as complete
 * anywhere in the app: user-created subjects are merged over it at runtime
 * (see persistence/userContent.ts), so nothing here is structurally special.
 *
 * `researchFields` are OpenAlex field ids (verified against
 * https://api.openalex.org/fields) and drive each lab's live research pane.
 */
export const SUBJECTS: Subject[] = [
  /* ---------------- ზუსტი მეცნიერებები ---------------- */
  {
    id: 'math',
    name: { ka: 'მათემატიკა', en: 'Mathematics' },
    tagline: { ka: 'ენა, რომლითაც სამყარო თავის წესებს ჰყვება' },
    group: 'exact',
    theme: { hue: 268, atmosphere: 'grid', glyph: '∑' },
    modules: ['formulaExplorer', 'puzzles'],
    researchFields: ['fields/26'],
    order: 1,
  },
  {
    id: 'algebra',
    name: { ka: 'ალგებრა', en: 'Algebra' },
    tagline: { ka: 'როცა უცნობს სახელს არქმევ, ის შენს ხელში ექცევა' },
    group: 'exact',
    theme: { hue: 258, atmosphere: 'grid', glyph: '𝑥' },
    researchFields: ['fields/26'],
    order: 2,
  },
  {
    id: 'geometry',
    name: { ka: 'გეომეტრია', en: 'Geometry' },
    tagline: { ka: 'ფორმის ლოგიკა — წერტილიდან სივრცემდე' },
    group: 'exact',
    theme: { hue: 208, atmosphere: 'grid', glyph: '△' },
    researchFields: ['fields/26'],
    order: 3,
  },
  {
    id: 'trigonometry',
    name: { ka: 'ტრიგონომეტრია', en: 'Trigonometry' },
    tagline: { ka: 'სამკუთხედი, რომელმაც ვარსკვლავებამდე მანძილი გაზომა' },
    group: 'exact',
    theme: { hue: 194, atmosphere: 'grid', glyph: '∿' },
    researchFields: ['fields/26'],
    order: 4,
  },
  {
    id: 'calculus',
    name: { ka: 'კალკულუსი', en: 'Calculus' },
    tagline: { ka: 'ცვლილების მათემატიკა — რა ხდება ზუსტად ამ წამს' },
    group: 'exact',
    theme: { hue: 286, atmosphere: 'grid', glyph: '∫' },
    researchFields: ['fields/26'],
    order: 5,
  },
  {
    id: 'statistics',
    name: { ka: 'სტატისტიკა', en: 'Statistics' },
    tagline: { ka: 'როგორ ვთქვათ სიმართლე ხმაურიან მონაცემებზე' },
    group: 'exact',
    theme: { hue: 172, atmosphere: 'grid', glyph: 'σ' },
    researchFields: ['fields/26', 'fields/18'],
    order: 6,
  },
  {
    id: 'probability',
    name: { ka: 'ალბათობა', en: 'Probability' },
    tagline: { ka: 'შემთხვევითობას საკუთარი, ძალიან მკაცრი წესები აქვს' },
    group: 'exact',
    theme: { hue: 158, atmosphere: 'grid', glyph: '⚄' },
    researchFields: ['fields/26'],
    order: 7,
  },

  /* ---------------- საბუნებისმეტყველო ---------------- */
  {
    id: 'physics',
    name: { ka: 'ფიზიკა', en: 'Physics' },
    tagline: { ka: 'წესები, რომლებსაც ყველაფერი ემორჩილება — ატომიდან გალაქტიკამდე' },
    group: 'natural',
    theme: { hue: 222, atmosphere: 'deep-space', glyph: '⚛' },
    modules: ['constants', 'simLab', 'formulaExplorer'],
    researchFields: ['fields/31'],
    order: 10,
  },
  {
    id: 'chemistry',
    name: { ka: 'ქიმია', en: 'Chemistry' },
    tagline: { ka: 'ნივთიერებები, რომლებიც ერთმანეთს სამუდამოდ ცვლიან' },
    group: 'natural',
    theme: { hue: 28, atmosphere: 'mineral', glyph: '⚗' },
    modules: ['periodicTable', 'safeDemos'],
    researchFields: ['fields/16'],
    order: 11,
  },
  {
    id: 'biology',
    name: { ka: 'ბიოლოგია', en: 'Biology' },
    tagline: { ka: 'როგორ ახერხებს მატერია ცოცხალი იყოს' },
    group: 'natural',
    theme: { hue: 142, atmosphere: 'organic', glyph: '🧬' },
    modules: ['researchFeed', 'codonLab'],
    researchFields: ['fields/13', 'fields/11'],
    order: 12,
  },
  {
    id: 'astronomy',
    name: { ka: 'ასტრონომია', en: 'Astronomy' },
    tagline: { ka: 'ღამის ცა, როგორც ყველაზე დიდი ლაბორატორია' },
    group: 'natural',
    theme: { hue: 248, atmosphere: 'deep-space', glyph: '✦' },
    modules: ['skyNow', 'scaleLab', 'apod'],
    researchFields: ['fields/31'],
    order: 13,
  },
  {
    id: 'ecology',
    name: { ka: 'ეკოლოგია', en: 'Ecology' },
    tagline: { ka: 'ცოცხალი სისტემები, რომლებიც ერთმანეთს ეყრდნობიან' },
    group: 'natural',
    theme: { hue: 122, atmosphere: 'organic', glyph: '🌿' },
    researchFields: ['fields/23'],
    order: 14,
  },
  {
    id: 'earth',
    name: { ka: 'დედამიწის მეცნიერებები', en: 'Earth Sciences' },
    tagline: { ka: 'პლანეტა, რომელზეც ვცხოვრობთ — როგორც შესასწავლი ობიექტი' },
    group: 'natural',
    theme: { hue: 196, atmosphere: 'mineral', glyph: '🜨' },
    modules: ['liveQuakes'],
    researchFields: ['fields/19'],
    order: 15,
  },
  {
    id: 'geology',
    name: { ka: 'გეოლოგია', en: 'Geology' },
    tagline: { ka: 'ქვა, რომელიც მილიარდი წლის ისტორიას ინახავს' },
    group: 'natural',
    theme: { hue: 24, atmosphere: 'mineral', glyph: '⛰' },
    researchFields: ['fields/19'],
    order: 16,
  },
  {
    id: 'meteorology',
    name: { ka: 'მეტეოროლოგია', en: 'Meteorology' },
    tagline: { ka: 'ატმოსფერო — ურთულესი სისტემა, რომელსაც ყოველდღე ვხედავთ' },
    group: 'natural',
    theme: { hue: 186, atmosphere: 'organic', glyph: '🌀' },
    researchFields: ['fields/19', 'fields/23'],
    order: 17,
  },

  /* ---------------- ტექნოლოგიები ---------------- */
  {
    id: 'cs',
    name: { ka: 'კომპიუტერული მეცნიერება', en: 'Computer Science' },
    tagline: { ka: 'როგორ ვასწავლით მანქანას ფიქრს' },
    group: 'technology',
    theme: { hue: 168, atmosphere: 'circuit', glyph: '⌘' },
    modules: ['codeLab', 'sortVisualizer'],
    researchFields: ['fields/17'],
    order: 20,
  },
  {
    id: 'programming',
    name: { ka: 'პროგრამირება', en: 'Programming' },
    tagline: { ka: 'იდეიდან მომუშავე პროგრამამდე' },
    group: 'technology',
    theme: { hue: 152, atmosphere: 'circuit', glyph: '{}' },
    modules: ['codeLab'],
    researchFields: ['fields/17'],
    order: 21,
  },
  {
    id: 'algorithms',
    name: { ka: 'ალგორითმები', en: 'Algorithms' },
    tagline: { ka: 'ნაბიჯები, რომლებიც ამოცანას ნამდვილად წყვეტენ' },
    group: 'technology',
    theme: { hue: 178, atmosphere: 'circuit', glyph: '⇄' },
    modules: ['sortVisualizer'],
    researchFields: ['fields/17'],
    order: 22,
  },
  {
    id: 'ai',
    name: { ka: 'ხელოვნური ინტელექტი', en: 'Artificial Intelligence' },
    tagline: { ka: 'მანქანები, რომლებიც მაგალითებისგან სწავლობენ' },
    group: 'technology',
    theme: { hue: 300, atmosphere: 'circuit', glyph: '◈' },
    researchFields: ['fields/17'],
    order: 23,
  },
  {
    id: 'robotics',
    name: { ka: 'რობოტიკა', en: 'Robotics' },
    tagline: { ka: 'მანქანა, რომელიც ფიზიკურ სამყაროს ეხება' },
    group: 'technology',
    theme: { hue: 16, atmosphere: 'circuit', glyph: '⚙' },
    researchFields: ['fields/22', 'fields/17'],
    order: 24,
  },
  {
    id: 'electronics',
    name: { ka: 'ელექტრონიკა', en: 'Electronics' },
    tagline: { ka: 'ელექტრონების მართვა, რომელმაც ყველაფერი შეცვალა' },
    group: 'technology',
    theme: { hue: 46, atmosphere: 'circuit', glyph: '⚡' },
    researchFields: ['fields/22'],
    order: 25,
  },
  {
    id: 'engineering',
    name: { ka: 'ინჟინერია', en: 'Engineering' },
    tagline: { ka: 'მეცნიერება, რომელიც რეალურ ობიექტად იქცევა' },
    group: 'technology',
    theme: { hue: 36, atmosphere: 'grid', glyph: '⌗' },
    researchFields: ['fields/22'],
    order: 26,
  },

  /* ---------------- ჰუმანიტარული ---------------- */
  {
    id: 'history',
    name: { ka: 'მსოფლიო ისტორია', en: 'World History' },
    tagline: { ka: 'არა თარიღები — მიზეზები და შედეგები' },
    group: 'humanities',
    theme: { hue: 32, atmosphere: 'archive', glyph: '⌛' },
    modules: ['timeline', 'onThisDay'],
    researchFields: ['fields/12'],
    order: 30,
  },
  {
    id: 'georgian-history',
    name: { ka: 'საქართველოს ისტორია', en: 'History of Georgia' },
    tagline: { ka: 'ჩვენი წარსული — წყაროებიდან, არა ლეგენდებიდან' },
    group: 'humanities',
    theme: { hue: 356, atmosphere: 'archive', glyph: '𐌂' },
    modules: ['timeline'],
    researchFields: ['fields/12'],
    order: 31,
  },
  {
    id: 'geography',
    name: { ka: 'გეოგრაფია', en: 'Geography' },
    tagline: { ka: 'რატომ არის სამყარო სწორედ ასე განაწილებული' },
    group: 'humanities',
    theme: { hue: 200, atmosphere: 'mineral', glyph: '🗺' },
    researchFields: ['fields/33', 'fields/19'],
    order: 32,
  },
  {
    id: 'philosophy',
    name: { ka: 'ფილოსოფია', en: 'Philosophy' },
    tagline: { ka: 'კითხვები, რომლებიც ჯერ არავის დაუხურავს' },
    group: 'humanities',
    theme: { hue: 274, atmosphere: 'archive', glyph: '☉' },
    researchFields: ['fields/12'],
    order: 33,
  },
  {
    id: 'psychology',
    name: { ka: 'ფსიქოლოგია', en: 'Psychology' },
    tagline: { ka: 'როგორ მუშაობს გონება, რომელიც ამას ახლა კითხულობს' },
    group: 'humanities',
    theme: { hue: 320, atmosphere: 'organic', glyph: '🧠' },
    researchFields: ['fields/32', 'fields/28'],
    order: 34,
  },
  {
    id: 'economics',
    name: { ka: 'ეკონომიკა', en: 'Economics' },
    tagline: { ka: 'არჩევანი, როცა ყველაფერი შეზღუდულია' },
    group: 'humanities',
    theme: { hue: 96, atmosphere: 'grid', glyph: '⇅' },
    researchFields: ['fields/20'],
    order: 35,
  },
  {
    id: 'civics',
    name: { ka: 'სამოქალაქო განათლება', en: 'Civics' },
    tagline: { ka: 'როგორ მუშაობს საზოგადოება, რომლის ნაწილიც ხარ' },
    group: 'humanities',
    theme: { hue: 212, atmosphere: 'archive', glyph: '⚖' },
    researchFields: ['fields/33'],
    order: 36,
  },

  /* ---------------- ენა და კულტურა ---------------- */
  {
    id: 'georgian-language',
    name: { ka: 'ქართული ენა', en: 'Georgian Language' },
    tagline: { ka: 'ენა, რომელსაც საკუთარი, არავისზე დაუმსგავსებელი ანბანი აქვს' },
    group: 'language',
    theme: { hue: 350, atmosphere: 'paper', glyph: 'ა' },
    researchFields: ['fields/12'],
    order: 40,
  },
  {
    id: 'georgian-literature',
    name: { ka: 'ქართული ლიტერატურა', en: 'Georgian Literature' },
    tagline: { ka: 'ტექსტები, რომლებმაც ჩვენი ენა ჩამოაყალიბეს' },
    group: 'language',
    theme: { hue: 12, atmosphere: 'paper', glyph: '📖' },
    researchFields: ['fields/12'],
    order: 41,
  },
  {
    id: 'world-literature',
    name: { ka: 'მსოფლიო ლიტერატურა', en: 'World Literature' },
    tagline: { ka: 'სხვისი ცხოვრება — შიგნიდან დანახული' },
    group: 'language',
    theme: { hue: 340, atmosphere: 'paper', glyph: '✒' },
    researchFields: ['fields/12'],
    order: 42,
  },
  {
    id: 'english',
    name: { ka: 'ინგლისური', en: 'English' },
    tagline: { ka: 'კარი, რომლის მიღმაც მსოფლიო ცოდნის უდიდესი ნაწილია' },
    group: 'language',
    theme: { hue: 218, atmosphere: 'paper', glyph: 'Aa' },
    researchFields: ['fields/12'],
    order: 43,
  },
  {
    id: 'linguistics',
    name: { ka: 'ლინგვისტიკა', en: 'Linguistics' },
    tagline: { ka: 'ენა, როგორც შესასწავლი სისტემა' },
    group: 'language',
    theme: { hue: 288, atmosphere: 'paper', glyph: '⟨⟩' },
    researchFields: ['fields/12'],
    order: 44,
  },
  {
    id: 'art-history',
    name: { ka: 'ხელოვნების ისტორია', en: 'Art History' },
    tagline: { ka: 'როგორ ხედავდნენ ადამიანები სამყაროს — საკუთარი ხელით' },
    group: 'language',
    theme: { hue: 8, atmosphere: 'archive', glyph: '🎨' },
    researchFields: ['fields/12'],
    order: 45,
  },
  {
    id: 'music',
    name: { ka: 'მუსიკა', en: 'Music' },
    tagline: { ka: 'მათემატიკა, რომელსაც ვგრძნობთ' },
    group: 'language',
    theme: { hue: 262, atmosphere: 'paper', glyph: '♪' },
    researchFields: ['fields/12'],
    order: 46,
  },
];

export const SUBJECT_GROUP_LABELS: Record<string, { ka: string; en?: string }> = {
  exact: { ka: 'ზუსტი მეცნიერებები', en: 'Exact sciences' },
  natural: { ka: 'საბუნებისმეტყველო მეცნიერებები', en: 'Natural sciences' },
  technology: { ka: 'ტექნოლოგიები', en: 'Technology' },
  humanities: { ka: 'ჰუმანიტარული მეცნიერებები', en: 'Humanities' },
  language: { ka: 'ენა და კულტურა', en: 'Language & culture' },
  custom: { ka: 'ჩემი ლაბორატორიები', en: 'My labs' },
};
